#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
LOCAL_BIN_DIR="${HOME}/.local/bin"

INSTALL_ROOT="${XDG_DATA_HOME}/teale"
CONFIG_ROOT="${XDG_CONFIG_HOME}/teale"
STATE_ROOT="${XDG_STATE_HOME}/teale"
APPLICATIONS_DIR="${XDG_DATA_HOME}/applications"
SERVICE_DIR="${XDG_CONFIG_HOME}/systemd/user"
DESKTOP_FILE="${APPLICATIONS_DIR}/teale.desktop"
WRAPPER_PATH="${LOCAL_BIN_DIR}/teale"
SERVICE_FILE="${SERVICE_DIR}/teale-node.service"

BIN_DIR="${INSTALL_ROOT}/bin"
SHARE_DIR="${INSTALL_ROOT}/share"
MODEL_DIR="${INSTALL_ROOT}/models"
LOG_DIR="${STATE_ROOT}/logs"
CONFIG_FILE="${CONFIG_ROOT}/teale-node.toml"
SUPABASE_CONFIG="${CONFIG_ROOT}/supabase-config.json"

require_runtime_libs() {
  if ! command -v ldd >/dev/null 2>&1; then
    return 0
  fi

  local missing
  missing="$(ldd "${SCRIPT_DIR}/bin/teale-tray" 2>/dev/null | grep 'not found' || true)"
  if [[ -z "${missing}" ]]; then
    return 0
  fi

  echo "teale-tray is missing Linux desktop runtime libraries:" >&2
  echo "${missing}" >&2
  echo >&2
  echo "Install the WebKitGTK runtime first. On Ubuntu or Debian:" >&2
  echo "  sudo apt-get update" >&2
  echo "  sudo apt-get install -y libgtk-3-0 libwebkit2gtk-4.1-0 libsoup-3.0-0 libvulkan1 xdg-utils desktop-file-utils" >&2
  exit 1
}

stage_files() {
  mkdir -p "${BIN_DIR}" "${SHARE_DIR}" "${MODEL_DIR}" "${CONFIG_ROOT}" "${LOG_DIR}" "${APPLICATIONS_DIR}" "${SERVICE_DIR}" "${LOCAL_BIN_DIR}"
  install -m 0755 "${SCRIPT_DIR}/bin/teale-node" "${BIN_DIR}/teale-node"
  install -m 0755 "${SCRIPT_DIR}/bin/teale-tray" "${BIN_DIR}/teale-tray"
  install -m 0755 "${SCRIPT_DIR}/bin/llama-server" "${BIN_DIR}/llama-server"
  install -m 0644 "${SCRIPT_DIR}/share/teale.png" "${SHARE_DIR}/teale.png"
  install -m 0644 "${SCRIPT_DIR}/config/supabase-config.json" "${SUPABASE_CONFIG}"
}

write_config_if_missing() {
  if [[ -f "${CONFIG_FILE}" ]]; then
    return 0
  fi

  local host_name threads
  host_name="$(hostname -s 2>/dev/null || hostname || echo "linux-device")"
  if command -v nproc >/dev/null 2>&1; then
    threads="$(nproc)"
  else
    threads="4"
  fi
  if [[ "${threads}" -gt 2 ]]; then
    threads="$((threads - 2))"
  else
    threads="2"
  fi

  python3 - "${SCRIPT_DIR}/config/supabase-config.json" "${CONFIG_FILE}" "${BIN_DIR}" "${CONFIG_ROOT}" "${host_name}" "${threads}" <<'PY'
import json
import pathlib
import sys

supabase_path, output_path, bin_dir, config_root, host_name, threads = sys.argv[1:]
try:
    supabase = json.loads(pathlib.Path(supabase_path).read_text(encoding="utf-8"))
except FileNotFoundError:
    supabase = {}

config = f'''# teale-node configuration -- auto-generated by the Linux desktop installer
[relay]
url = "wss://relay.teale.com/ws"

[llama]
binary = "{bin_dir}/llama-server"
model = ""
gpu_layers = 999
context_size = 8192
port = 11436
extra_args = ["--threads", "{threads}"]

[control]
port = 11437
registry_path = "{config_root}/model-registry.json"
supabase_url = "{supabase.get("supabase_url", "")}"
supabase_anon_key = "{supabase.get("supabase_anon_key", "")}"
supabase_redirect_url = "{supabase.get("supabase_redirect_url", "teale://auth/callback")}"

[node]
display_name = "{host_name}"
'''
pathlib.Path(output_path).write_text(config, encoding="utf-8")
PY
}

write_wrapper() {
  cat > "${WRAPPER_PATH}" <<EOF
#!/usr/bin/env bash
exec "${BIN_DIR}/teale-tray" "\$@"
EOF
  chmod 0755 "${WRAPPER_PATH}"
}

write_desktop_entry() {
  cat > "${DESKTOP_FILE}" <<EOF
[Desktop Entry]
Type=Application
Name=Teale
Comment=Local and network inference companion
Exec=${BIN_DIR}/teale-tray %u
Icon=${SHARE_DIR}/teale.png
Terminal=false
Categories=Utility;Network;
MimeType=x-scheme-handler/teale;
StartupNotify=true
StartupWMClass=Teale
EOF

  if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "${APPLICATIONS_DIR}" >/dev/null 2>&1 || true
  fi
  if command -v xdg-mime >/dev/null 2>&1; then
    xdg-mime default "$(basename "${DESKTOP_FILE}")" x-scheme-handler/teale || true
  fi
}

write_service() {
  cat > "${SERVICE_FILE}" <<EOF
[Unit]
Description=Teale node
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${INSTALL_ROOT}
ExecStart=${BIN_DIR}/teale-node --config ${CONFIG_FILE}
Restart=always
RestartSec=5
Environment=HOME=%h
Environment=RUST_LOG=info
StandardOutput=append:${LOG_DIR}/teale-node.log
StandardError=append:${LOG_DIR}/teale-node.log

[Install]
WantedBy=default.target
EOF
}

start_service_if_available() {
  if ! command -v systemctl >/dev/null 2>&1; then
    echo "systemctl is not available; start Teale manually with:" >&2
    echo "  ${BIN_DIR}/teale-node --config ${CONFIG_FILE}" >&2
    return 0
  fi

  if ! systemctl --user show-environment >/dev/null 2>&1; then
    echo "A systemd user session is not active." >&2
    echo "After logging into a desktop session, run:" >&2
    echo "  systemctl --user daemon-reload" >&2
    echo "  systemctl --user enable --now teale-node.service" >&2
    return 0
  fi

  systemctl --user daemon-reload
  systemctl --user enable --now teale-node.service
}

launch_desktop_if_available() {
  if [[ -z "${DISPLAY:-}" && -z "${WAYLAND_DISPLAY:-}" ]]; then
    return 0
  fi

  "${BIN_DIR}/teale-tray" >/dev/null 2>&1 &
}

require_runtime_libs
stage_files
write_config_if_missing
write_wrapper
write_desktop_entry
write_service
start_service_if_available
launch_desktop_if_available

echo "Teale installed."
echo "Desktop launcher: Teale"
echo "Config: ${CONFIG_FILE}"
echo "Node service: ${SERVICE_FILE}"
