// Auto-generated by scripts/generate-version.sh — do not edit manually.
public enum BuildVersion {
    public static let commit = "c2f300b"
    public static let date = "2026-06-29 02:08 UTC"
    public static let branch = "codex/bump-desktop-release-version"
    public static let display = "c2f300b (2026-06-29 02:08 UTC)"
}
