// Auto-generated by scripts/generate-version.sh — do not edit manually.
public enum BuildVersion {
    public static let commit = "7d8f831"
    public static let date = "2026-04-24 17:05 UTC"
    public static let branch = "taylorhou/mac-win-parity"
    public static let display = "7d8f831 (2026-04-24 17:05 UTC)"
}
