// Auto-generated by scripts/generate-version.sh — do not edit manually.
public enum BuildVersion {
    public static let commit = "2aff873"
    public static let date = "2026-04-16 02:21 UTC"
    public static let branch = "main"
    public static let display = "2aff873 (2026-04-16 02:21 UTC)"
}
