#!/bin/sh
# Generate BuildVersion.swift with git commit hash and build date.
# Called before swift build or xcodebuild.

set -e

OUTFILE="Sources/SharedTypes/BuildVersion.swift"
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
DATE=$(date -u '+%Y-%m-%d %H:%M UTC')
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

# Release tag (e.g. mac-v2026.09.04.2345) stamped by mac-app-release.yml.
# Dev/local builds have no tag and fall back to commit + build date.
TAG="${TEALE_RELEASE_TAG:-}"
VERSION_LABEL="${TAG#mac-v}"
if [ -n "$VERSION_LABEL" ]; then
    DISPLAY="$VERSION_LABEL ($COMMIT)"
else
    DISPLAY="$COMMIT ($DATE)"
fi

cat > "$OUTFILE" << EOF
// Auto-generated by scripts/generate-version.sh — do not edit manually.
public enum BuildVersion {
    public static let commit = "$COMMIT"
    public static let date = "$DATE"
    public static let branch = "$BRANCH"
    public static let releaseTag = "$TAG"
    public static let display = "$DISPLAY"
}
EOF
