import Foundation
import AppCore

private enum CompanionCopy {
    static func string(_ key: String, language: AppLanguage, fallback: String) -> String {
        tables[language]?[key] ?? fallback
    }

    private static let tables: [AppLanguage: [String: String]] = [
        .spanish: spanish,
        .portugueseBrazil: portugueseBrazil,
        .filipinoPhilippines: filipinoPhilippines,
    ]

    private static let spanish: [String: String] = [
        "nav.home": "teale",
        "nav.supply": "supply",
        "nav.demand": "demand",
        "nav.wallet": "wallet",
        "nav.account": "account",
        "settings.language": "Idioma",
        "settings.display": "Display",
        "settings.updates": "Updates",
        "settings.autoDownloadUpdatesDetail": "Download new macOS releases in the background.",
        "settings.autoInstallUpdatesDetail": "Replace Teale.app and relaunch when the download is ready.",
        "settings.credits": "Créditos",
        "settings.usd": "USD",
        "header.home": "oferta y demanda de inferencia distribuida de IA",
        "header.supply.credits": "gana créditos de teale aportando inferencia de IA a usuarios de todo el mundo",
        "header.supply.usd": "gana saldo equivalente en usd aportando inferencia de IA a usuarios de todo el mundo",
        "header.demand.credits": "usa modelos locales gratis o compra y gasta créditos para modelos más potentes",
        "header.demand.usd": "usa modelos locales gratis o compra y gasta usd para modelos más potentes",
        "header.wallet": "balances del dispositivo, envío de activos e historial del ledger",
        "header.account": "wallet de cuenta, wallets de dispositivos vinculados y detalles del perfil",
        "footer.tagline": "teale.com - inferencia distribuida de IA para el mundo",
        "home.overview": "overview",
        "home.network": "network",
        "home.thread": "thread",
        "home.lede": "Teale convierte esta máquina en un nodo de oferta y un cliente de demanda al mismo tiempo.",
        "common.state": "Estado",
        "common.model": "Modelo",
        "common.wallet": "Wallet",
        "common.account": "Cuenta",
        "common.totalDevices": "Dispositivos totales",
        "common.totalRAM": "RAM total",
        "common.totalModels": "Modelos totales",
        "common.avgTTFT": "TTFT prom.",
        "common.avgTPS": "TPS prom.",
        "common.totalUSDCDistributed": "USDC total distribuido",
        "home.avgTPS.note": "Estimado a partir del hardware que está en línea ahora.",
        "home.waitingGatewayStats": "Esperando estadísticas activas del gateway.",
        "account.authUnavailable": "Auth unavailable",
        "account.authUnavailableDetail": "El inicio de sesión no está disponible en esta build.",
        "account.notSignedIn": "No has iniciado sesión",
        "account.signedIn": "Sesión iniciada",
        "supply.status": "status",
        "supply.earnings": "earnings",
        "supply.recommended": "recommended",
        "supply.transfer": "transfer",
        "supply.catalog": "catalog",
        "supply.machine": "Máquina",
        "supply.ram": "RAM",
        "supply.backend": "Backend",
        "supply.power": "Energía",
        "supply.unloadCurrent": "Unload current model",
        "supply.rate": "Rate",
        "supply.availability": "Availability",
        "supply.availabilityNote": "Earned for keeping a loaded model online and available to the network.",
        "supply.servedInference": "Served inference",
        "supply.servedSplitValue": "95% / 5%",
        "supply.servedSplitNote": "95% goes to this device and 5% goes to Teale when this machine serves the request.",
        "supply.session": "Session",
        "supply.openWallet": "Open wallet",
        "supply.waitingLoadedModel": "Esperando un modelo cargado...",
        "supply.waitingPricing": "Esperando precios activos de la red...",
        "supply.walletNote": "La vista wallet muestra el balance en tiempo real.",
        "supply.noCompatibleModel": "No se encontró un modelo compatible",
        "supply.machineDoesNotFit": "Esta máquina todavía no entra en el catálogo.",
        "supply.highestDemand": "Mayor demanda",
        "supply.highestDemandDetail": "Coincide con la clasificación actual de demanda.",
        "supply.largestFit": "Mayor ajuste",
        "supply.largestFitDetail": "Usa el modelo más grande que esta máquina puede mantener en memoria.",
        "supply.fetchingWeights": "Descargando pesos desde HuggingFace",
        "supply.noCompatibleModelsYet": "Todavía no hay modelos compatibles para este dispositivo.",
        "demand.local": "local inference",
        "demand.networkModels": "teale network models",
        "demand.network": "teale network",
        "demand.baseURL": "Base URL",
        "demand.bearer": "Bearer",
        "demand.selected": "Selected",
        "demand.copyLocalCurl": "Copy local curl",
        "demand.copyBearer": "Copy bearer token",
        "demand.copyNetworkCurl": "Copy network curl",
        "demand.waitingLocalModel": "Esperando un modelo local...",
        "demand.waitingBearer": "Esperando el bearer del dispositivo desde la sincronización del gateway wallet.",
        "demand.noLiveModels": "Todavía no hay datos de modelos activos de la red.",
        "demand.liveDevices": "device(s) activos",
        "demand.requestsUseBearer": "Las solicitudes usan automáticamente el bearer de este dispositivo.",
        "demand.requestsSpend": "Tus solicitudes gastan {{unit}} usando automáticamente el bearer de este dispositivo.",
        "demand.bearerCopied": "Bearer copiado.",
        "wallet.balances": "balances",
        "wallet.send": "send",
        "wallet.ledger": "ledger",
        "wallet.usdc": "USDC",
        "wallet.session": "Session",
        "wallet.lifetimeEarned": "Lifetime earned",
        "wallet.lifetimeSpent": "Lifetime spent",
        "wallet.requests": "Requests",
        "wallet.balanceNote": "El balance sube mientras supply está activo.",
        "wallet.sessionNote": "Las ganancias comienzan cuando hay un modelo compatible cargado y sirviendo.",
        "wallet.recipient": "Recipient",
        "wallet.amount": "Amount",
        "wallet.memo": "Memo",
        "wallet.recipientPlaceholder": "full device wallet id or account wallet id",
        "wallet.memoPlaceholder": "nota opcional",
        "wallet.sendAction": "send",
        "wallet.sending": "sending...",
        "wallet.sendNote": "Usa solo IDs completos. Esta wallet del dispositivo puede enviar a un ID completo de wallet de cuenta o a un ID de wallet de dispositivo de 64 caracteres a través del gateway de Teale.",
        "wallet.noTransactions": "Todavía no hay transacciones. Sirve un modelo para empezar a ganar.",
        "wallet.exportCSV": "export csv",
        "wallet.enterCredits": "Introduce una cantidad entera de créditos.",
        "wallet.enterUSD": "Introduce una cantidad en USD mayor que 0.",
        "wallet.enterRecipient": "Primero introduce un destinatario.",
        "wallet.exceedsBalance": "Eso supera el balance de este wallet del dispositivo.",
        "wallet.sentPrefix": "Sent",
        "wallet.exportedCSV": "CSV exportado en",
        "wallet.exportFailed": "No se pudo exportar el CSV:",
        "account.account": "account",
        "account.wallet": "account wallet",
        "account.send": "send from account wallet",
        "account.details": "details",
        "account.devices": "devices",
        "account.ledger": "account ledger",
        "account.status": "Status",
        "account.signIn": "Sign in",
        "account.signOut": "Sign out",
        "account.linkNote": "Inicia sesión para vincular esta máquina a una persona. Las ganancias del wallet del dispositivo siguen funcionando sin inicio de sesión humano.",
        "account.syncing": "Vinculando este perfil firmado con la wallet de cuenta del gateway.",
        "account.signInForWallet": "Inicia sesión para cargar la wallet de cuenta.",
        "account.loadingWallet": "Sincronizando la wallet de cuenta del gateway para este dispositivo.",
        "account.unavailableWallet": "La wallet de cuenta del gateway todavía no está disponible para este dispositivo.",
        "account.userID": "User ID",
        "account.email": "Email",
        "account.phone": "Phone",
        "account.device": "Device",
        "account.hardware": "Hardware",
        "account.walletBalance": "Account balance",
        "account.walletBalanceNote": "Los barridos de las wallets de dispositivos vinculados llegan aquí primero.",
        "account.walletUSDC": "USDC",
        "account.accountWalletID": "Account wallet ID",
        "account.accountWalletCopied": "Account wallet ID copied.",
        "account.accountWalletIDNote": "Haz clic para copiar. Comparte este ID completo cuando deban enviar créditos a la wallet de cuenta.",
        "account.recipientPlaceholder": "full device wallet id or account wallet id",
        "account.sendNote": "Usa solo IDs completos. Esta wallet de cuenta puede enviar a un ID completo de wallet de cuenta o a un ID de wallet de dispositivo de 64 caracteres.",
        "account.exceedsBalance": "Eso supera el balance de esta wallet de cuenta.",
        "account.sweptSuccess": "Moved {{amount}} into the account wallet.",
        "account.nothingToSweep": "Esta wallet de dispositivo no tiene nada para barrer.",
        "account.sweeping": "sweeping...",
        "account.sweep": "sweep",
        "account.deviceWalletIDNote": "Haz clic para copiar el ID completo de la wallet del dispositivo vinculado.",
        "account.noTransactions": "Todavía no llegaron transferencias ni barridos a la wallet de cuenta.",
        "account.currentVersion": "Current version",
        "account.updateStatus": "Update status",
        "account.autoDownloadUpdates": "download updates automatically",
        "account.autoInstallUpdates": "install after download",
        "account.checkUpdates": "check now",
        "account.viewRelease": "view release",
        "account.installingUpdate": "installing...",
        "account.downloadingUpdate": "downloading...",
        "account.installDownloadedUpdate": "install downloaded update",
        "account.installUpdate": "install update",
        "account.viewDevicesSignedOut": "Inicia sesión para ver los dispositivos de esta cuenta.",
        "account.noDevices": "Todavía no se encontraron dispositivos vinculados.",
        "chat.model": "MODEL",
        "chat.message": "MESSAGE",
        "chat.newThread": "new thread",
        "chat.creatingThread": "Creando tu primer hilo...",
        "chat.empty": "Abre un hilo y pregúntale cualquier cosa a Teale.",
        "chat.thinking": "Pensando...",
        "chat.streaming": "streaming",
        "chat.interrupted": "interrumpido",
        "chat.hint": "El chat con hilos es local primero. Elige un modelo arriba para decidir la ruta.",
        "chat.send": "send",
        "chat.localFree": "Local es gratis en este Mac.",
        "chat.networkSpend": "Los modelos de red gastan {{unit}}. El bearer del dispositivo se usa automáticamente.",
        "chat.respondedVia": "Respuesta vía {{model}}.",
        "chat.invalidResponse": "El stream local del chat devolvió una respuesta inválida.",
        "chat.newThreadTitle": "New Thread",
        "common.noModelLoaded": "No model loaded",
        "common.waitingWANLatency": "Esperando latencia WAN",
        "common.waitingServingNodes": "Esperando nodos activos",
    ]

    private static let portugueseBrazil: [String: String] = [
        "nav.home": "teale",
        "nav.supply": "supply",
        "nav.demand": "demand",
        "nav.wallet": "wallet",
        "nav.account": "account",
        "settings.language": "Idioma",
        "settings.display": "Display",
        "settings.updates": "Updates",
        "settings.autoDownloadUpdatesDetail": "Baixe novas releases do macOS em segundo plano.",
        "settings.autoInstallUpdatesDetail": "Substitua o Teale.app e relance quando o download estiver pronto.",
        "settings.credits": "Créditos",
        "settings.usd": "USD",
        "header.home": "oferta e demanda de inferência distribuída de IA",
        "header.supply.credits": "ganhe créditos da teale fornecendo inferência de IA para usuários do mundo todo",
        "header.supply.usd": "ganhe saldo equivalente em usd fornecendo inferência de IA para usuários do mundo todo",
        "header.demand.credits": "use modelos locais de graça ou compre e gaste créditos em modelos mais poderosos",
        "header.demand.usd": "use modelos locais de graça ou compre e gaste usd em modelos mais poderosos",
        "header.wallet": "saldos do dispositivo, envio de ativos e histórico do ledger",
        "header.account": "wallet da conta, wallets dos dispositivos vinculados e detalhes do perfil",
        "footer.tagline": "teale.com - inferência distribuída de IA para o mundo",
        "home.overview": "overview",
        "home.network": "network",
        "home.thread": "thread",
        "home.lede": "A Teale transforma esta máquina em um nó de oferta e um cliente de demanda ao mesmo tempo.",
        "common.state": "Estado",
        "common.model": "Modelo",
        "common.wallet": "Wallet",
        "common.account": "Conta",
        "common.totalDevices": "Dispositivos totais",
        "common.totalRAM": "RAM total",
        "common.totalModels": "Modelos totais",
        "common.avgTTFT": "TTFT méd.",
        "common.avgTPS": "TPS méd.",
        "common.totalUSDCDistributed": "USDC total distribuído",
        "home.avgTPS.note": "Estimado com base no hardware que está online agora.",
        "home.waitingGatewayStats": "Aguardando estatísticas ativas do gateway.",
        "account.authUnavailable": "Auth unavailable",
        "account.authUnavailableDetail": "O login não está disponível nesta build.",
        "account.notSignedIn": "Sem login",
        "account.signedIn": "Sessão iniciada",
        "supply.status": "status",
        "supply.earnings": "earnings",
        "supply.recommended": "recommended",
        "supply.transfer": "transfer",
        "supply.catalog": "catalog",
        "supply.machine": "Máquina",
        "supply.ram": "RAM",
        "supply.backend": "Backend",
        "supply.power": "Energia",
        "supply.unloadCurrent": "Unload current model",
        "supply.rate": "Rate",
        "supply.availability": "Availability",
        "supply.availabilityNote": "Ganho por manter um modelo carregado online e disponível para a rede.",
        "supply.servedInference": "Served inference",
        "supply.servedSplitValue": "95% / 5%",
        "supply.servedSplitNote": "95% vai para este dispositivo e 5% vai para a Teale quando esta máquina atende a requisição.",
        "supply.session": "Session",
        "supply.openWallet": "Open wallet",
        "supply.waitingLoadedModel": "Aguardando um modelo carregado...",
        "supply.waitingPricing": "Aguardando preços ativos da rede...",
        "supply.walletNote": "A wallet mostra o saldo crescer em tempo real.",
        "supply.noCompatibleModel": "Nenhum modelo compatível encontrado",
        "supply.machineDoesNotFit": "Esta máquina ainda não cabe no catálogo.",
        "supply.highestDemand": "Maior demanda",
        "supply.highestDemandDetail": "Corresponde ao ranking atual de demanda.",
        "supply.largestFit": "Maior ajuste",
        "supply.largestFitDetail": "Usa o maior modelo que esta máquina consegue manter em memória.",
        "supply.fetchingWeights": "Baixando pesos do HuggingFace",
        "supply.noCompatibleModelsYet": "Ainda não há modelos compatíveis para este dispositivo.",
        "demand.local": "local inference",
        "demand.networkModels": "teale network models",
        "demand.network": "teale network",
        "demand.baseURL": "Base URL",
        "demand.bearer": "Bearer",
        "demand.selected": "Selected",
        "demand.copyLocalCurl": "Copy local curl",
        "demand.copyBearer": "Copy bearer token",
        "demand.copyNetworkCurl": "Copy network curl",
        "demand.waitingLocalModel": "Aguardando um modelo local...",
        "demand.waitingBearer": "Aguardando o bearer do dispositivo vindo da sincronização da wallet no gateway.",
        "demand.noLiveModels": "Ainda não há dados de modelos ativos da rede.",
        "demand.liveDevices": "device(s) ativos",
        "demand.requestsUseBearer": "As solicitações usam automaticamente o bearer deste dispositivo.",
        "demand.requestsSpend": "Suas solicitações gastam {{unit}} usando automaticamente o bearer deste dispositivo.",
        "demand.bearerCopied": "Bearer copiado.",
        "wallet.balances": "balances",
        "wallet.send": "send",
        "wallet.ledger": "ledger",
        "wallet.usdc": "USDC",
        "wallet.session": "Session",
        "wallet.lifetimeEarned": "Lifetime earned",
        "wallet.lifetimeSpent": "Lifetime spent",
        "wallet.requests": "Requests",
        "wallet.balanceNote": "O saldo aumenta enquanto o supply está ativo.",
        "wallet.sessionNote": "Os ganhos começam quando um modelo compatível está carregado e servindo.",
        "wallet.recipient": "Recipient",
        "wallet.amount": "Amount",
        "wallet.memo": "Memo",
        "wallet.recipientPlaceholder": "full device wallet id or account wallet id",
        "wallet.memoPlaceholder": "nota opcional",
        "wallet.sendAction": "send",
        "wallet.sending": "sending...",
        "wallet.sendNote": "Use apenas IDs completos. Esta wallet do dispositivo pode enviar para um ID completo de wallet da conta ou para um ID de wallet do dispositivo com 64 caracteres pelo gateway da Teale.",
        "wallet.noTransactions": "Ainda não há transações. Sirva um modelo para começar a ganhar.",
        "wallet.exportCSV": "export csv",
        "wallet.enterCredits": "Digite um valor inteiro de créditos.",
        "wallet.enterUSD": "Digite um valor em USD maior que 0.",
        "wallet.enterRecipient": "Digite um destinatário primeiro.",
        "wallet.exceedsBalance": "Isso excede o saldo desta wallet do dispositivo.",
        "wallet.sentPrefix": "Sent",
        "wallet.exportedCSV": "CSV exportado para",
        "wallet.exportFailed": "Não foi possível exportar o CSV:",
        "account.account": "account",
        "account.wallet": "account wallet",
        "account.send": "send from account wallet",
        "account.details": "details",
        "account.devices": "devices",
        "account.ledger": "account ledger",
        "account.status": "Status",
        "account.signIn": "Sign in",
        "account.signOut": "Sign out",
        "account.linkNote": "Faça login para vincular esta máquina a uma pessoa. Os ganhos da wallet do dispositivo continuam funcionando sem login humano.",
        "account.syncing": "Vinculando este perfil à wallet da conta no gateway.",
        "account.signInForWallet": "Faça login para carregar a wallet da conta.",
        "account.loadingWallet": "Sincronizando a wallet da conta do gateway para este dispositivo.",
        "account.unavailableWallet": "A wallet da conta do gateway ainda não está disponível para este dispositivo.",
        "account.userID": "User ID",
        "account.email": "Email",
        "account.phone": "Phone",
        "account.device": "Device",
        "account.hardware": "Hardware",
        "account.walletBalance": "Account balance",
        "account.walletBalanceNote": "As varreduras das wallets de dispositivos vinculados chegam aqui primeiro.",
        "account.walletUSDC": "USDC",
        "account.accountWalletID": "Account wallet ID",
        "account.accountWalletCopied": "Account wallet ID copied.",
        "account.accountWalletIDNote": "Clique para copiar. Compartilhe este ID completo quando alguém precisar enviar créditos para a wallet da conta.",
        "account.recipientPlaceholder": "full device wallet id or account wallet id",
        "account.sendNote": "Use apenas IDs completos. Esta wallet da conta pode enviar para um ID completo de wallet da conta ou para um ID de wallet do dispositivo com 64 caracteres.",
        "account.exceedsBalance": "Isso excede o saldo desta wallet da conta.",
        "account.sweptSuccess": "Moved {{amount}} into the account wallet.",
        "account.nothingToSweep": "Esta wallet do dispositivo não tem nada para varrer.",
        "account.sweeping": "sweeping...",
        "account.sweep": "sweep",
        "account.deviceWalletIDNote": "Clique para copiar o ID completo da wallet do dispositivo vinculado.",
        "account.noTransactions": "Ainda não chegaram transferências nem varreduras à wallet da conta.",
        "account.currentVersion": "Current version",
        "account.updateStatus": "Update status",
        "account.autoDownloadUpdates": "download updates automatically",
        "account.autoInstallUpdates": "install after download",
        "account.checkUpdates": "check now",
        "account.viewRelease": "view release",
        "account.installingUpdate": "installing...",
        "account.downloadingUpdate": "downloading...",
        "account.installDownloadedUpdate": "install downloaded update",
        "account.installUpdate": "install update",
        "account.viewDevicesSignedOut": "Faça login para ver os dispositivos desta conta.",
        "account.noDevices": "Nenhum dispositivo vinculado encontrado ainda.",
        "chat.model": "MODEL",
        "chat.message": "MESSAGE",
        "chat.newThread": "new thread",
        "chat.creatingThread": "Criando seu primeiro thread...",
        "chat.empty": "Abra um thread e pergunte qualquer coisa para a Teale.",
        "chat.thinking": "Pensando...",
        "chat.streaming": "streaming",
        "chat.interrupted": "interrompido",
        "chat.hint": "O chat em threads é local primeiro. Escolha um modelo acima para definir a rota.",
        "chat.send": "send",
        "chat.localFree": "Local é grátis neste Mac.",
        "chat.networkSpend": "Os modelos de rede gastam {{unit}}. O bearer do dispositivo é usado automaticamente.",
        "chat.respondedVia": "Resposta via {{model}}.",
        "chat.invalidResponse": "O stream local do chat retornou uma resposta inválida.",
        "chat.newThreadTitle": "New Thread",
        "common.noModelLoaded": "No model loaded",
        "common.waitingWANLatency": "Aguardando latência WAN",
        "common.waitingServingNodes": "Aguardando nós ativos",
    ]

    private static let filipinoPhilippines: [String: String] = [
        "nav.home": "teale",
        "nav.supply": "supply",
        "nav.demand": "demand",
        "nav.wallet": "wallet",
        "nav.account": "account",
        "settings.language": "Wika",
        "settings.display": "Display",
        "settings.updates": "Updates",
        "settings.autoDownloadUpdatesDetail": "I-download sa background ang mga bagong macOS release.",
        "settings.autoInstallUpdatesDetail": "Palitan ang Teale.app at i-relaunch kapag handa na ang download.",
        "settings.credits": "Credits",
        "settings.usd": "USD",
        "header.home": "distributed ai inference supply and demand",
        "header.supply.credits": "kumita ng teale credits sa pagbibigay ng ai inference sa mga user sa buong mundo",
        "header.supply.usd": "kumita ng usd-equivalent balance sa pagbibigay ng ai inference sa mga user sa buong mundo",
        "header.demand.credits": "gumamit ng local models nang libre o bumili at gumastos ng credits para sa mas malalakas na modelo",
        "header.demand.usd": "gumamit ng local models nang libre o bumili at gumastos ng usd para sa mas malalakas na modelo",
        "header.wallet": "device balances, send assets, at ledger history",
        "header.account": "account wallet, linked device wallets, and profile details",
        "footer.tagline": "teale.com - distributed ai inference for the world",
        "home.overview": "overview",
        "home.network": "network",
        "home.thread": "thread",
        "home.lede": "Ginagawang supply node at demand client ang machine na ito ng Teale nang sabay.",
        "common.state": "State",
        "common.model": "Model",
        "common.wallet": "Wallet",
        "common.account": "Account",
        "common.totalDevices": "Kabuuang devices",
        "common.totalRAM": "Kabuuang RAM",
        "common.totalModels": "Kabuuang models",
        "common.avgTTFT": "Avg TTFT",
        "common.avgTPS": "Avg TPS",
        "common.totalUSDCDistributed": "Kabuuang naipamahaging USDC",
        "home.avgTPS.note": "Tinatayang batay sa hardware na online ngayon.",
        "home.waitingGatewayStats": "Naghihintay ng live gateway stats.",
        "account.authUnavailable": "Auth unavailable",
        "account.authUnavailableDetail": "Hindi available ang sign-in sa build na ito.",
        "account.notSignedIn": "Hindi naka-sign in",
        "account.signedIn": "Naka-sign in",
        "supply.status": "status",
        "supply.earnings": "earnings",
        "supply.recommended": "recommended",
        "supply.transfer": "transfer",
        "supply.catalog": "catalog",
        "supply.machine": "Machine",
        "supply.ram": "RAM",
        "supply.backend": "Backend",
        "supply.power": "Power",
        "supply.unloadCurrent": "Unload current model",
        "supply.rate": "Rate",
        "supply.availability": "Availability",
        "supply.availabilityNote": "Kinikita ito sa pagpapanatiling online at available sa network ang loaded model.",
        "supply.servedInference": "Served inference",
        "supply.servedSplitValue": "95% / 5%",
        "supply.servedSplitNote": "95% ay napupunta sa device na ito at 5% ay napupunta sa Teale kapag ang machine na ito ang nagsilbi ng request.",
        "supply.session": "Session",
        "supply.openWallet": "Open wallet",
        "supply.waitingLoadedModel": "Naghihintay ng loaded model...",
        "supply.waitingPricing": "Naghihintay ng live network pricing...",
        "supply.walletNote": "Makikita sa wallet ang paglaki ng balance sa real time.",
        "supply.noCompatibleModel": "Walang compatible model na nakita",
        "supply.machineDoesNotFit": "Hindi pa kasya ang machine na ito sa catalog.",
        "supply.highestDemand": "Pinakamataas na demand",
        "supply.highestDemandDetail": "Tumutugma sa kasalukuyang demand ranking.",
        "supply.largestFit": "Pinakamalaking kasya",
        "supply.largestFitDetail": "Ginagamit ang pinakamalaking model na kasya sa memory ng machine na ito.",
        "supply.fetchingWeights": "Kumukuha ng weights mula sa HuggingFace",
        "supply.noCompatibleModelsYet": "Wala pang compatible models para sa device na ito.",
        "demand.local": "local inference",
        "demand.networkModels": "teale network models",
        "demand.network": "teale network",
        "demand.baseURL": "Base URL",
        "demand.bearer": "Bearer",
        "demand.selected": "Selected",
        "demand.copyLocalCurl": "Copy local curl",
        "demand.copyBearer": "Copy bearer token",
        "demand.copyNetworkCurl": "Copy network curl",
        "demand.waitingLocalModel": "Naghihintay ng local model...",
        "demand.waitingBearer": "Naghihintay ng bearer ng device mula sa gateway wallet sync.",
        "demand.noLiveModels": "Wala pang live network model data.",
        "demand.liveDevices": "live na device(s)",
        "demand.requestsUseBearer": "Awtomatikong ginagamit ng requests ang bearer ng device na ito.",
        "demand.requestsSpend": "Ang requests mo ay gumagastos ng {{unit}} gamit ang bearer ng device na ito.",
        "demand.bearerCopied": "Nakopya ang bearer token.",
        "wallet.balances": "balances",
        "wallet.send": "send",
        "wallet.ledger": "ledger",
        "wallet.usdc": "USDC",
        "wallet.session": "Session",
        "wallet.lifetimeEarned": "Lifetime earned",
        "wallet.lifetimeSpent": "Lifetime spent",
        "wallet.requests": "Requests",
        "wallet.balanceNote": "Tumataas ang balance habang naka-on ang supply.",
        "wallet.sessionNote": "Nagsisimula ang earnings kapag may compatible model na loaded at serving.",
        "wallet.recipient": "Recipient",
        "wallet.amount": "Amount",
        "wallet.memo": "Memo",
        "wallet.recipientPlaceholder": "full device wallet id or account wallet id",
        "wallet.memoPlaceholder": "optional note",
        "wallet.sendAction": "send",
        "wallet.sending": "sending...",
        "wallet.sendNote": "Buong wallet IDs lang ang gamitin. Puwedeng magpadala ang device wallet na ito sa buong account wallet ID o sa 64-char device wallet ID sa pamamagitan ng Teale gateway.",
        "wallet.noTransactions": "Wala pang transactions. Mag-serve ng model para magsimulang kumita.",
        "wallet.exportCSV": "export csv",
        "wallet.enterCredits": "Maglagay ng buong bilang ng credits.",
        "wallet.enterUSD": "Maglagay ng USD amount na mas mataas sa 0.",
        "wallet.enterRecipient": "Maglagay muna ng recipient.",
        "wallet.exceedsBalance": "Lagpas ito sa balance ng device wallet na ito.",
        "wallet.sentPrefix": "Sent",
        "wallet.exportedCSV": "Na-export ang CSV sa",
        "wallet.exportFailed": "Hindi ma-export ang CSV:",
        "account.account": "account",
        "account.wallet": "account wallet",
        "account.send": "send from account wallet",
        "account.details": "details",
        "account.devices": "devices",
        "account.ledger": "account ledger",
        "account.status": "Status",
        "account.signIn": "Sign in",
        "account.signOut": "Sign out",
        "account.linkNote": "Mag-sign in para i-link ang machine na ito sa isang tao. Patuloy pa ring gagana ang device wallet earnings kahit walang human sign-in.",
        "account.syncing": "Nililink ang signed-in na profile na ito sa gateway account wallet.",
        "account.signInForWallet": "Mag-sign in para i-load ang account wallet.",
        "account.loadingWallet": "Sini-sync ang gateway account wallet para sa device na ito.",
        "account.unavailableWallet": "Hindi pa available ang gateway account wallet para sa device na ito.",
        "account.userID": "User ID",
        "account.email": "Email",
        "account.phone": "Phone",
        "account.device": "Device",
        "account.hardware": "Hardware",
        "account.walletBalance": "Account balance",
        "account.walletBalanceNote": "Dito muna pumapasok ang sweeps mula sa linked device wallets.",
        "account.walletUSDC": "USDC",
        "account.accountWalletID": "Account wallet ID",
        "account.accountWalletCopied": "Account wallet ID copied.",
        "account.accountWalletIDNote": "I-click para makopya. Ibahagi ang buong account wallet ID na ito kapag may magpapadala ng credits sa account wallet.",
        "account.recipientPlaceholder": "full device wallet id or account wallet id",
        "account.sendNote": "Buong wallet IDs lang ang gamitin. Puwedeng magpadala ang account wallet na ito sa buong account wallet ID o sa 64-char device wallet ID.",
        "account.exceedsBalance": "Lumalagpas ito sa balance ng account wallet na ito.",
        "account.sweptSuccess": "Moved {{amount}} into the account wallet.",
        "account.nothingToSweep": "Walang masi-sweep sa device wallet na ito.",
        "account.sweeping": "sweeping...",
        "account.sweep": "sweep",
        "account.deviceWalletIDNote": "I-click para makopya ang buong linked device wallet ID.",
        "account.noTransactions": "Wala pang transfer o sweep na dumating sa account wallet.",
        "account.currentVersion": "Current version",
        "account.updateStatus": "Update status",
        "account.autoDownloadUpdates": "download updates automatically",
        "account.autoInstallUpdates": "install after download",
        "account.checkUpdates": "check now",
        "account.viewRelease": "view release",
        "account.installingUpdate": "installing...",
        "account.downloadingUpdate": "downloading...",
        "account.installDownloadedUpdate": "install downloaded update",
        "account.installUpdate": "install update",
        "account.viewDevicesSignedOut": "Mag-sign in para makita ang mga device sa account na ito.",
        "account.noDevices": "Wala pang linked devices na nakita.",
        "chat.model": "MODEL",
        "chat.message": "MESSAGE",
        "chat.newThread": "new thread",
        "chat.creatingThread": "Ginagawa ang unang thread mo...",
        "chat.empty": "Magbukas ng thread at magtanong kay Teale.",
        "chat.thinking": "Nag-iisip...",
        "chat.streaming": "streaming",
        "chat.interrupted": "naputol",
        "chat.hint": "Local-first ang threaded chat. Pumili ng model sa itaas para itakda ang ruta.",
        "chat.send": "send",
        "chat.localFree": "Libre ang local sa Mac na ito.",
        "chat.networkSpend": "Gumagastos ng {{unit}} ang network models. Awtomatikong ginagamit ang bearer ng device.",
        "chat.respondedVia": "Sumagot sa pamamagitan ng {{model}}.",
        "chat.invalidResponse": "Nagbalik ng invalid response ang local chat stream.",
        "chat.newThreadTitle": "New Thread",
        "common.noModelLoaded": "No model loaded",
        "common.waitingWANLatency": "Naghihintay ng WAN latency",
        "common.waitingServingNodes": "Naghihintay ng serving nodes",
    ]
}

extension AppState {
    func companionText(_ key: String, fallback: String) -> String {
        CompanionCopy.string(key, language: language, fallback: fallback)
    }

    func companionText(_ key: String, fallback: String, replacements: [String: String]) -> String {
        var value = companionText(key, fallback: fallback)
        for (name, replacement) in replacements {
            value = value.replacingOccurrences(of: "{{\(name)}}", with: replacement)
        }
        return value
    }

    func companionMenuLabel(for unit: CompanionDisplayUnit) -> String {
        switch unit {
        case .credits:
            return companionText("settings.credits", fallback: "Credits")
        case .usd:
            return companionText("settings.usd", fallback: "USD")
        }
    }
}
