/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/index',
        'getting-started/install-mac',
        'getting-started/install-cli',
        'getting-started/install-cross-platform',
        'getting-started/quickstart-chat',
        'getting-started/quickstart-api',
        'getting-started/quickstart-earn',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/how-teale-works',
        'concepts/inference-providers',
        'concepts/networking',
        'concepts/credit-economy',
        'concepts/private-tealenet',
        'concepts/security-model',
        'concepts/mixture-of-models',
        'concepts/agent-protocol',
        'concepts/group-chat',
        'concepts/solana-settlement',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/index',
        'guides/earn-credits',
        'guides/setup-ptn',
        'guides/use-with-conductor',
        'guides/use-with-openai-sdk',
        'guides/use-with-continue-dev',
        'guides/connect-ios-companion',
        'guides/lan-cluster',
        'guides/wan-networking',
        'guides/manage-models',
        'guides/api-keys',
        'guides/wallet-and-payments',
        'guides/integrate-tealeSdk',
        'guides/headless-server',
      ],
    },
    {
      type: 'category',
      label: 'CLI Reference',
      items: [
        'cli/index',
        'cli/up',
        'cli/down',
        'cli/serve',
        'cli/status',
        'cli/chat',
        'cli/login',
        'cli/models',
        'cli/config',
        'cli/ptn',
        'cli/wallet',
        'cli/peers',
        'cli/agent',
        'cli/apikeys',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/index',
        'api/chat-completions',
        'api/models',
        'api/health',
        'api/app-snapshot',
        'api/app-settings',
        'api/app-models',
        'api/app-ptn',
        'api/app-wallet',
        'api/app-peers',
        'api/app-agent',
        'api/app-apikeys',
      ],
    },
    {
      type: 'category',
      label: 'Protocol',
      items: [
        'protocol/index',
        'protocol/relay-wire-protocol',
        'protocol/cluster-messages',
        'protocol/node-capabilities',
        'protocol/ed25519-identity',
        'protocol/noise-encryption',
        'protocol/ptn-certificates',
        'protocol/nat-traversal',
        'protocol/pricing-protocol',
      ],
    },
    {
      type: 'category',
      label: 'TealeSDK',
      items: [
        'sdk/index',
        'sdk/getting-started',
        'sdk/teale-contributor',
        'sdk/contribution-options',
        'sdk/consent-flow',
        'sdk/earnings-reporting',
        'sdk/swiftui-integration',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/hardware-tiers',
        'reference/supported-models',
        'reference/pricing-tables',
        'reference/error-codes',
        'reference/ports-and-endpoints',
        'reference/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Self-Hosting',
      items: [
        'self-hosting/relay-server',
        'self-hosting/relay-scaling',
      ],
    },
    'faq',
  ],
};
