// Auto-generated by scripts/generate-version.sh — do not edit manually.
public enum BuildVersion {
    public static let commit = "05b1b60"
    public static let date = "2026-04-12 21:51 UTC"
    public static let branch = "taylorhou/usdc-more-decimals"
    public static let display = "05b1b60 (2026-04-12 21:51 UTC)"
}
