import Foundation

// MARK: - Supported Languages

public enum AppLanguage: String, CaseIterable, Codable, Identifiable {
    case english = "en"
    case chineseSimplified = "zh-Hans"
    case japanese = "ja"
    case spanish = "es"
    case french = "fr"

    public var id: String { rawValue }

    public var displayName: String {
        switch self {
        case .english: return "English"
        case .chineseSimplified: return "中文（简体）"
        case .japanese: return "日本語"
        case .spanish: return "Español"
        case .french: return "Français"
        }
    }
}

// MARK: - Localization Helper

enum L {
    static func string(_ key: String, language: AppLanguage) -> String {
        strings[language]?[key] ?? strings[.english]?[key] ?? key
    }

    private static let strings: [AppLanguage: [String: String]] = [
        .english: en,
        .chineseSimplified: zhHans,
        .japanese: ja,
        .spanish: es,
        .french: fr,
    ]

    // MARK: - English

    private static let en: [String: String] = [
        // Sidebar
        "sidebar.dashboard": "Dashboard",
        "sidebar.chat": "Chat",
        "sidebar.models": "Models",
        "sidebar.network": "Network",
        "sidebar.cluster": "Cluster",
        "sidebar.wan": "WAN",
        "sidebar.wallet": "Wallet",
        "sidebar.devices": "Devices",
        "sidebar.settings": "Settings",

        // Dashboard
        "dashboard.title": "Dashboard",
        "dashboard.hardware": "Hardware",
        "dashboard.engine": "Engine",
        "dashboard.noModelLoaded": "No model loaded",
        "dashboard.browseModels": "Browse Models",
        "dashboard.unload": "Unload",
        "dashboard.quickActions": "Quick Actions",
        "dashboard.newChat": "New Chat",
        "dashboard.copyAPIURL": "Copy API URL",
        "dashboard.cluster": "Cluster",
        "dashboard.wan": "WAN Network",
        "dashboard.credits": "Credits",
        "dashboard.view": "View",
        "dashboard.searchingPeers": "Searching for peers...",
        "dashboard.devices": "%d devices",
        "dashboard.total": "%d GB total",
        "dashboard.wanPeers": "%d WAN peers",
        "dashboard.connectingWAN": "Connecting to WAN network...",
        "dashboard.api": "API",
        "dashboard.throttle": "Throttle",

        // Chat
        "chat.title": "Chat",
        "chat.placeholder": "Type a message...",
        "chat.send": "Send",
        "chat.thinking": "Thinking...",
        "chat.noModel": "Load a model to start chatting",
        "chat.you": "You",
        "chat.assistant": "Assistant",
        "chat.newConversation": "New Conversation",
        "chat.noModelLoaded": "No model loaded.",
        "chat.goToModels": "Go to **Models** to download and load one.",
        "chat.startConversation": "Start a conversation",
        "chat.typeBelow": "Type a message below to begin",
        "chat.noModelResponse": "No model loaded. Go to Models to download and load one.",
        "chat.message": "Message...",

        // Models
        "models.title": "Models",
        "models.search": "Search models...",
        "models.available": "%d models available for your hardware",
        "models.gbAvailable": "%d GB available",
        "models.load": "Load",
        "models.unload": "Unload",
        "models.download": "Download",
        "models.switchModel": "Switch Model?",
        "models.switchConfirm": "This will unload the current model and load %@.",
        "models.switchButton": "Switch",
        "models.cancel": "Cancel",
        "models.downloadComplete": "Download Complete",
        "models.readyToLoad": "%@ is ready. Load it now? This will unload the current model.",
        "models.notNow": "Not Now",
        "models.preparing": "Preparing…",
        "models.loaded": "LOADED",
        "models.checking": "CHECKING",
        "models.loading": "LOADING",
        "models.downloading": "DL",
        "models.ready": "READY",

        // Wallet
        "wallet.title": "Wallet",
        "wallet.balance": "Credit Balance",
        "wallet.credits": "credits",
        "wallet.sendCredits": "Send Credits",
        "wallet.connectCluster": "Connect to a cluster to send credits to peers",
        "wallet.selectPeer": "Select peer...",
        "wallet.amount": "Amount",
        "wallet.memo": "Memo (optional)",
        "wallet.send": "Send",
        "wallet.whatCanBuy": "What Can Your Credits Buy?",
        "wallet.quickQuestion": "Quick question",
        "wallet.quickQuestionDetail": "A short back-and-forth conversation",
        "wallet.writeEmail": "Write an email or essay",
        "wallet.writeEmailDetail": "A few paragraphs of generated text",
        "wallet.debugCode": "Help debug code",
        "wallet.debugCodeDetail": "Paste code, get an explanation and fix",
        "wallet.summarize": "Summarize a long document",
        "wallet.summarizeDetail": "Feed in pages of text, get a summary",
        "wallet.balancePlenty": "You have plenty of credits for heavy daily use.",
        "wallet.balanceGood": "Enough for dozens of conversations.",
        "wallet.balanceOk": "Good for several conversations today.",
        "wallet.balanceLow": "Running low — earn more by serving other nodes.",
        "wallet.balanceEmpty": "No credits yet. Enable the cluster to start earning.",
        "wallet.pricingFooter": "Costs vary by model size — smaller models are cheaper, larger ones give better answers. You earn credits automatically when other devices use your Mac for inference.",
        "wallet.summary": "Summary",
        "wallet.earned": "Earned",
        "wallet.spent": "Spent",
        "wallet.recentTransactions": "Recent Transactions",
        "wallet.noTransactions": "No transactions yet",

        // Settings
        "settings.title": "Settings",
        "settings.account": "Account",
        "settings.notSignedIn": "Not signed in",
        "settings.signInSubtitle": "Sign in to sync devices and back up your wallet",
        "settings.signIn": "Sign In",
        "settings.signOut": "Sign Out",
        "settings.localMode": "Local mode",
        "settings.localModeSubtitle": "Configure Supabase to enable sign-in and device sync",
        "settings.general": "General",
        "settings.language": "Language",
        "settings.launchAtLogin": "Launch at Login",
        "settings.lanCluster": "LAN Cluster",
        "settings.enableLAN": "Enable LAN Discovery",
        "settings.clusterPasscode": "Cluster Passcode:",
        "settings.optional": "Optional",
        "settings.peersConnected": "%d peer(s) connected",
        "settings.searchingPeers": "Searching for peers...",
        "settings.orgReservation": "Org capacity reservation: %d%%",
        "settings.orgReservationHelp": "Nodes with the same passcode form your organization. Reserved capacity serves org members first.",
        "settings.wanP2P": "WAN P2P Network",
        "settings.enableWAN": "Enable WAN",
        "settings.relayServer": "Relay Server:",
        "settings.wanPeers": "%d WAN peer(s)",
        "settings.connectingRelay": "Connecting to relay...",
        "settings.natType": "NAT Type",
        "settings.contributionSchedule": "Contribution Schedule",
        "settings.preset": "Preset",
        "settings.onlyPluggedIn": "Only when plugged in",
        "settings.onlyWiFi": "Only on Wi-Fi",
        "settings.editSchedule": "Edit Schedule",
        "settings.hideSchedule": "Hide Schedule",
        "settings.scheduleHelp": "Controls when your machine serves network requests. Local inference is always available.",
        "settings.credits": "Credits",
        "settings.balance": "Balance",
        "settings.totalEarned": "Total Earned",
        "settings.totalSpent": "Total Spent",
        "settings.viewWallet": "View Wallet",
        "settings.modelStorage": "Model Storage",
        "settings.maxStorage": "Maximum storage: %d GB",
        "settings.hardware": "Hardware",
        "settings.chip": "Chip",
        "settings.ram": "RAM",
        "settings.gpuCores": "GPU Cores",
        "settings.memBandwidth": "Memory Bandwidth",
        "settings.deviceTier": "Device Tier",
        "settings.about": "About",
        "settings.version": "Version",
        "settings.engine": "Engine",
        "settings.sourceCode": "Source Code",
        "settings.keepAwake": "Keep Mac Awake",
        "settings.keepAwakeHelp": "Prevents your Mac from sleeping so it stays online for the inference pool. Your screen can still turn off.",
        "settings.quit": "Quit Teale",

        // Solana Wallet
        "settings.solanaWallet": "Solana Wallet",
        "settings.enableSolana": "Enable USDC Wallet",
        "settings.solanaNetwork": "Network",
        "settings.solanaAddress": "Wallet Address",
        "settings.usdcBalance": "USDC Balance",
        "settings.solanaMonitoring": "Monitoring for deposits",
        "settings.solanaStopped": "Monitoring stopped",
        "settings.solanaHelp": "Connect your credits to Solana USDC. 10,000 credits = $1 USDC. Deposits and withdrawals are on-chain.",
        "wallet.solana.title": "Solana Wallet",
        "wallet.solana.address": "Your Deposit Address",
        "wallet.solana.onChainBalance": "On-Chain USDC",
        "wallet.solana.depositTitle": "Deposit USDC",
        "wallet.solana.depositInstructions": "Send USDC (SPL) on Solana to your address above. Deposits are detected automatically and converted to credits at 10,000 credits per $1 USDC.",
        "wallet.solana.withdrawTitle": "Withdraw as USDC",
        "wallet.solana.creditsAmount": "Credits",
        "wallet.solana.destinationAddress": "Solana address",
        "wallet.solana.withdrawButton": "Withdraw",

        // Connect Agent
        "agent.connect": "Connect Your Agent",
        "agent.serverRunning": "API Server Running",
        "agent.serverStarting": "API Server Starting...",
        "agent.generateKey": "Generate API Key",
        "agent.saveKeyWarning": "Save this key — it won't be shown again",
        "agent.quickSetup": "Quick Setup",
        "agent.advanced": "Advanced",
        "agent.revoked": "Revoked",
        "agent.revoke": "Revoke",
        "agent.generateAnother": "Generate Another Key",
        "agent.allowNetwork": "Allow Network Access",
        "agent.networkOn": "Accepting requests from other devices on the network",
        "agent.networkOff": "Only accepting requests from this Mac (localhost)",
        "agent.footer": "Works with any OpenAI-compatible client — Claude Code, Cursor, Hermes, OpenClaw, Python SDK, and more.",

        // Cluster View
        "cluster.title": "LAN Cluster",
        "cluster.enable": "Enable Cluster",
        "cluster.searchingDevices": "Searching for devices on your network...",
        "cluster.connectedPeers": "Connected Peers",
        "cluster.noPeers": "No peers discovered yet",

        // WAN View
        "wan.title": "WAN P2P Network",
        "wan.enable": "Enable WAN",
        "wan.connectedPeers": "Connected Peers",
        "wan.noPeers": "No WAN peers connected",

        // Common
        "common.copy": "Copy",
        "common.copied": "Copied",
        "common.phone": "Phone",
        "common.email": "Email",
        "common.devices": "Devices",
        "common.signingIn": "Signing in...",

        // Days
        "day.mon": "Mon",
        "day.tue": "Tue",
        "day.wed": "Wed",
        "day.thu": "Thu",
        "day.fri": "Fri",
        "day.sat": "Sat",
        "day.sun": "Sun",

        // Thermal / Power
        "thermal.nominal": "Nominal",
        "thermal.fair": "Fair",
        "thermal.serious": "Serious",
        "thermal.critical": "Critical",
        "power.ac": "AC Power",
        "power.battery": "Battery",
    ]

    // MARK: - Chinese (Simplified)

    private static let zhHans: [String: String] = [
        "sidebar.dashboard": "仪表盘",
        "sidebar.chat": "聊天",
        "sidebar.models": "模型",
        "sidebar.network": "网络",
        "sidebar.cluster": "集群",
        "sidebar.wan": "广域网",
        "sidebar.wallet": "钱包",
        "sidebar.devices": "设备",
        "sidebar.settings": "设置",

        "dashboard.title": "仪表盘",
        "dashboard.hardware": "硬件",
        "dashboard.engine": "引擎",
        "dashboard.noModelLoaded": "未加载模型",
        "dashboard.browseModels": "浏览模型",
        "dashboard.unload": "卸载",
        "dashboard.quickActions": "快捷操作",
        "dashboard.newChat": "新聊天",
        "dashboard.copyAPIURL": "复制 API 地址",
        "dashboard.cluster": "集群",
        "dashboard.wan": "广域网",
        "dashboard.credits": "积分",
        "dashboard.view": "查看",
        "dashboard.searchingPeers": "正在搜索节点...",
        "dashboard.devices": "%d 台设备",
        "dashboard.total": "%d GB 总计",
        "dashboard.wanPeers": "%d 个广域网节点",
        "dashboard.connectingWAN": "正在连接广域网...",
        "dashboard.api": "API",
        "dashboard.throttle": "节流",

        "chat.title": "聊天",
        "chat.placeholder": "输入消息...",
        "chat.send": "发送",
        "chat.thinking": "思考中...",
        "chat.noModel": "加载模型以开始聊天",
        "chat.you": "你",
        "chat.assistant": "助手",
        "chat.newConversation": "新对话",
        "chat.noModelLoaded": "未加载模型。",
        "chat.goToModels": "前往**模型**下载并加载一个。",
        "chat.startConversation": "开始对话",
        "chat.typeBelow": "在下方输入消息开始",
        "chat.noModelResponse": "未加载模型。前往模型页面下载并加载一个。",
        "chat.message": "消息...",

        "models.title": "模型",
        "models.search": "搜索模型...",
        "models.available": "%d 个模型适合您的硬件",
        "models.gbAvailable": "%d GB 可用",
        "models.load": "加载",
        "models.unload": "卸载",
        "models.download": "下载",
        "models.switchModel": "切换模型？",
        "models.switchConfirm": "这将卸载当前模型并加载 %@。",
        "models.switchButton": "切换",
        "models.cancel": "取消",
        "models.downloadComplete": "下载完成",
        "models.readyToLoad": "%@ 已就绪。是否立即加载？这将卸载当前模型。",
        "models.notNow": "暂不",
        "models.preparing": "准备中…",
        "models.loaded": "已加载",
        "models.checking": "检查中",
        "models.loading": "加载中",
        "models.downloading": "下载",
        "models.ready": "就绪",

        "wallet.title": "钱包",
        "wallet.balance": "积分余额",
        "wallet.credits": "积分",
        "wallet.sendCredits": "发送积分",
        "wallet.connectCluster": "连接集群以向节点发送积分",
        "wallet.selectPeer": "选择节点...",
        "wallet.amount": "金额",
        "wallet.memo": "备注（可选）",
        "wallet.send": "发送",
        "wallet.whatCanBuy": "您的积分可以做什么？",
        "wallet.quickQuestion": "快速提问",
        "wallet.quickQuestionDetail": "一段简短的对话",
        "wallet.writeEmail": "写邮件或文章",
        "wallet.writeEmailDetail": "生成几段文字",
        "wallet.debugCode": "调试代码",
        "wallet.debugCodeDetail": "粘贴代码，获取解释和修复",
        "wallet.summarize": "总结长文档",
        "wallet.summarizeDetail": "输入大量文本，获取摘要",
        "wallet.balancePlenty": "您有充足的积分，可以大量使用。",
        "wallet.balanceGood": "足够进行数十次对话。",
        "wallet.balanceOk": "够今天进行几次对话。",
        "wallet.balanceLow": "余额不多了——为其他节点提供推理来赚取更多。",
        "wallet.balanceEmpty": "还没有积分。启用集群开始赚取。",
        "wallet.pricingFooter": "费用因模型大小而异——小模型更便宜，大模型回答更好。当其他设备使用您的 Mac 进行推理时，您会自动赚取积分。",
        "wallet.summary": "摘要",
        "wallet.earned": "已赚取",
        "wallet.spent": "已花费",
        "wallet.recentTransactions": "最近交易",
        "wallet.noTransactions": "暂无交易记录",

        "settings.title": "设置",
        "settings.account": "账户",
        "settings.notSignedIn": "未登录",
        "settings.signInSubtitle": "登录以同步设备和备份钱包",
        "settings.signIn": "登录",
        "settings.signOut": "退出登录",
        "settings.localMode": "本地模式",
        "settings.localModeSubtitle": "配置 Supabase 以启用登录和设备同步",
        "settings.general": "通用",
        "settings.language": "语言",
        "settings.launchAtLogin": "登录时启动",
        "settings.lanCluster": "局域网集群",
        "settings.enableLAN": "启用局域网发现",
        "settings.clusterPasscode": "集群密码：",
        "settings.optional": "可选",
        "settings.peersConnected": "%d 个节点已连接",
        "settings.searchingPeers": "正在搜索节点...",
        "settings.orgReservation": "组织容量预留：%d%%",
        "settings.orgReservationHelp": "使用相同密码的节点组成您的组织。预留容量优先服务组织成员。",
        "settings.wanP2P": "广域网 P2P 网络",
        "settings.enableWAN": "启用广域网",
        "settings.relayServer": "中继服务器：",
        "settings.wanPeers": "%d 个广域网节点",
        "settings.connectingRelay": "正在连接中继...",
        "settings.natType": "NAT 类型",
        "settings.contributionSchedule": "贡献时间表",
        "settings.preset": "预设",
        "settings.onlyPluggedIn": "仅在充电时",
        "settings.onlyWiFi": "仅在 Wi-Fi 下",
        "settings.editSchedule": "编辑时间表",
        "settings.hideSchedule": "隐藏时间表",
        "settings.scheduleHelp": "控制您的机器何时处理网络请求。本地推理始终可用。",
        "settings.credits": "积分",
        "settings.balance": "余额",
        "settings.totalEarned": "总赚取",
        "settings.totalSpent": "总花费",
        "settings.viewWallet": "查看钱包",
        "settings.modelStorage": "模型存储",
        "settings.maxStorage": "最大存储：%d GB",
        "settings.hardware": "硬件",
        "settings.chip": "芯片",
        "settings.ram": "内存",
        "settings.gpuCores": "GPU 核心",
        "settings.memBandwidth": "内存带宽",
        "settings.deviceTier": "设备等级",
        "settings.about": "关于",
        "settings.version": "版本",
        "settings.engine": "引擎",
        "settings.sourceCode": "源代码",
        "settings.keepAwake": "保持 Mac 唤醒",
        "settings.keepAwakeHelp": "防止 Mac 进入睡眠状态，使其始终在线为推理池提供服务。屏幕仍然可以关闭。",
        "settings.quit": "退出 Teale",
        "settings.solanaWallet": "Solana 钱包",
        "settings.enableSolana": "启用 USDC 钱包",
        "settings.solanaNetwork": "网络",
        "settings.solanaAddress": "钱包地址",
        "settings.usdcBalance": "USDC 余额",
        "settings.solanaMonitoring": "正在监控存款",
        "settings.solanaStopped": "监控已停止",
        "settings.solanaHelp": "将积分连接到 Solana USDC。10,000 积分 = $1 USDC。存取款均在链上进行。",
        "wallet.solana.title": "Solana 钱包",
        "wallet.solana.address": "您的存款地址",
        "wallet.solana.onChainBalance": "链上 USDC",
        "wallet.solana.depositTitle": "存入 USDC",
        "wallet.solana.depositInstructions": "将 USDC (SPL) 发送到上方的 Solana 地址。存款会自动检测并按 10,000 积分兑 $1 USDC 的比例转换为积分。",
        "wallet.solana.withdrawTitle": "提取为 USDC",
        "wallet.solana.creditsAmount": "积分",
        "wallet.solana.destinationAddress": "Solana 地址",
        "wallet.solana.withdrawButton": "提取",

        "agent.connect": "连接您的 Agent",
        "agent.serverRunning": "API 服务器运行中",
        "agent.serverStarting": "API 服务器启动中...",
        "agent.generateKey": "生成 API 密钥",
        "agent.saveKeyWarning": "请保存此密钥——不会再次显示",
        "agent.quickSetup": "快速设置",
        "agent.advanced": "高级",
        "agent.revoked": "已吊销",
        "agent.revoke": "吊销",
        "agent.generateAnother": "生成另一个密钥",
        "agent.allowNetwork": "允许网络访问",
        "agent.networkOn": "接受网络上其他设备的请求",
        "agent.networkOff": "仅接受本机请求（localhost）",
        "agent.footer": "兼容任何 OpenAI 客户端——Claude Code、Cursor、Hermes、OpenClaw、Python SDK 等。",

        "cluster.title": "局域网集群",
        "cluster.enable": "启用集群",
        "cluster.searchingDevices": "正在搜索网络上的设备...",
        "cluster.connectedPeers": "已连接的节点",
        "cluster.noPeers": "尚未发现节点",

        "wan.title": "广域网 P2P 网络",
        "wan.enable": "启用广域网",
        "wan.connectedPeers": "已连接的节点",
        "wan.noPeers": "未连接广域网节点",

        "common.copy": "复制",
        "common.copied": "已复制",
        "common.phone": "电话",
        "common.email": "邮箱",
        "common.devices": "设备",
        "common.signingIn": "登录中...",

        "day.mon": "周一",
        "day.tue": "周二",
        "day.wed": "周三",
        "day.thu": "周四",
        "day.fri": "周五",
        "day.sat": "周六",
        "day.sun": "周日",

        "thermal.nominal": "正常",
        "thermal.fair": "一般",
        "thermal.serious": "严重",
        "thermal.critical": "危急",
        "power.ac": "电源",
        "power.battery": "电池",
    ]

    // MARK: - Japanese

    private static let ja: [String: String] = [
        "sidebar.dashboard": "ダッシュボード",
        "sidebar.chat": "チャット",
        "sidebar.models": "モデル",
        "sidebar.network": "ネットワーク",
        "sidebar.cluster": "クラスタ",
        "sidebar.wan": "WAN",
        "sidebar.wallet": "ウォレット",
        "sidebar.devices": "デバイス",
        "sidebar.settings": "設定",

        "dashboard.title": "ダッシュボード",
        "dashboard.hardware": "ハードウェア",
        "dashboard.engine": "エンジン",
        "dashboard.noModelLoaded": "モデル未読込",
        "dashboard.browseModels": "モデルを探す",
        "dashboard.unload": "解放",
        "dashboard.quickActions": "クイック操作",
        "dashboard.newChat": "新しいチャット",
        "dashboard.copyAPIURL": "API URLをコピー",
        "dashboard.cluster": "クラスタ",
        "dashboard.wan": "WANネットワーク",
        "dashboard.credits": "クレジット",
        "dashboard.view": "表示",
        "dashboard.searchingPeers": "ピアを検索中...",
        "dashboard.devices": "%d 台のデバイス",
        "dashboard.total": "合計 %d GB",
        "dashboard.wanPeers": "%d WANピア",
        "dashboard.connectingWAN": "WANネットワークに接続中...",
        "dashboard.api": "API",
        "dashboard.throttle": "スロットル",

        "chat.title": "チャット",
        "chat.placeholder": "メッセージを入力...",
        "chat.send": "送信",
        "chat.thinking": "考え中...",
        "chat.noModel": "チャットを始めるにはモデルを読み込んでください",
        "chat.you": "あなた",
        "chat.assistant": "アシスタント",
        "chat.newConversation": "新しい会話",
        "chat.noModelLoaded": "モデルが読み込まれていません。",
        "chat.goToModels": "**モデル**からダウンロードして読み込んでください。",
        "chat.startConversation": "会話を始めましょう",
        "chat.typeBelow": "下にメッセージを入力して開始",
        "chat.noModelResponse": "モデルが読み込まれていません。モデルページからダウンロードして読み込んでください。",
        "chat.message": "メッセージ...",

        "models.title": "モデル",
        "models.search": "モデルを検索...",
        "models.available": "お使いのハードウェアに対応する%d個のモデル",
        "models.gbAvailable": "%d GB 利用可能",
        "models.load": "読込",
        "models.unload": "解放",
        "models.download": "ダウンロード",
        "models.switchModel": "モデルを切り替えますか？",
        "models.switchConfirm": "現在のモデルを解放して%@を読み込みます。",
        "models.switchButton": "切替",
        "models.cancel": "キャンセル",
        "models.downloadComplete": "ダウンロード完了",
        "models.readyToLoad": "%@の準備ができました。今すぐ読み込みますか？現在のモデルは解放されます。",
        "models.notNow": "後で",
        "models.preparing": "準備中…",
        "models.loaded": "読込済",
        "models.checking": "確認中",
        "models.loading": "読込中",
        "models.downloading": "DL中",
        "models.ready": "準備完了",

        "wallet.title": "ウォレット",
        "wallet.balance": "クレジット残高",
        "wallet.credits": "クレジット",
        "wallet.sendCredits": "クレジットを送る",
        "wallet.connectCluster": "クラスタに接続してピアにクレジットを送信",
        "wallet.selectPeer": "ピアを選択...",
        "wallet.amount": "金額",
        "wallet.memo": "メモ（任意）",
        "wallet.send": "送信",
        "wallet.whatCanBuy": "クレジットで何ができる？",
        "wallet.quickQuestion": "ちょっとした質問",
        "wallet.quickQuestionDetail": "短いやり取りの会話",
        "wallet.writeEmail": "メールや文章を書く",
        "wallet.writeEmailDetail": "数段落のテキスト生成",
        "wallet.debugCode": "コードのデバッグ",
        "wallet.debugCodeDetail": "コードを貼り付けて解説と修正を取得",
        "wallet.summarize": "長い文書の要約",
        "wallet.summarizeDetail": "大量のテキストを入力して要約を取得",
        "wallet.balancePlenty": "たっぷりのクレジットがあります。",
        "wallet.balanceGood": "数十回の会話に十分です。",
        "wallet.balanceOk": "今日の数回の会話に十分です。",
        "wallet.balanceLow": "残り少なめ——他のノードに推論を提供して稼ぎましょう。",
        "wallet.balanceEmpty": "クレジットがありません。クラスタを有効にして稼ぎましょう。",
        "wallet.pricingFooter": "コストはモデルサイズによって異なります。小さいモデルは安く、大きいモデルはより良い回答を生成します。他のデバイスがあなたのMacで推論を行うと自動的にクレジットを獲得できます。",
        "wallet.summary": "サマリー",
        "wallet.earned": "獲得",
        "wallet.spent": "使用",
        "wallet.recentTransactions": "最近の取引",
        "wallet.noTransactions": "取引履歴なし",

        "settings.title": "設定",
        "settings.account": "アカウント",
        "settings.notSignedIn": "未ログイン",
        "settings.signInSubtitle": "デバイス同期とウォレットバックアップのためにログイン",
        "settings.signIn": "ログイン",
        "settings.signOut": "ログアウト",
        "settings.localMode": "ローカルモード",
        "settings.localModeSubtitle": "Supabaseを設定してログインとデバイス同期を有効に",
        "settings.general": "一般",
        "settings.language": "言語",
        "settings.launchAtLogin": "ログイン時に起動",
        "settings.lanCluster": "LANクラスタ",
        "settings.enableLAN": "LAN検出を有効にする",
        "settings.clusterPasscode": "クラスタパスコード：",
        "settings.optional": "任意",
        "settings.peersConnected": "%d ピア接続中",
        "settings.searchingPeers": "ピアを検索中...",
        "settings.orgReservation": "組織容量予約：%d%%",
        "settings.orgReservationHelp": "同じパスコードのノードが組織を形成します。予約容量は組織メンバーを優先します。",
        "settings.wanP2P": "WAN P2Pネットワーク",
        "settings.enableWAN": "WANを有効にする",
        "settings.relayServer": "リレーサーバー：",
        "settings.wanPeers": "%d WANピア",
        "settings.connectingRelay": "リレーに接続中...",
        "settings.natType": "NATタイプ",
        "settings.contributionSchedule": "貢献スケジュール",
        "settings.preset": "プリセット",
        "settings.onlyPluggedIn": "充電中のみ",
        "settings.onlyWiFi": "Wi-Fi接続時のみ",
        "settings.editSchedule": "スケジュールを編集",
        "settings.hideSchedule": "スケジュールを隠す",
        "settings.scheduleHelp": "マシンがネットワークリクエストを処理するタイミングを制御します。ローカル推論は常に利用可能です。",
        "settings.credits": "クレジット",
        "settings.balance": "残高",
        "settings.totalEarned": "合計獲得",
        "settings.totalSpent": "合計使用",
        "settings.viewWallet": "ウォレットを見る",
        "settings.modelStorage": "モデルストレージ",
        "settings.maxStorage": "最大容量：%d GB",
        "settings.hardware": "ハードウェア",
        "settings.chip": "チップ",
        "settings.ram": "RAM",
        "settings.gpuCores": "GPUコア",
        "settings.memBandwidth": "メモリ帯域幅",
        "settings.deviceTier": "デバイスティア",
        "settings.about": "このアプリについて",
        "settings.version": "バージョン",
        "settings.engine": "エンジン",
        "settings.sourceCode": "ソースコード",
        "settings.keepAwake": "Macをスリープさせない",
        "settings.keepAwakeHelp": "Macがスリープしないようにして、推論プールにオンラインで参加し続けます。画面はオフにできます。",
        "settings.quit": "Tealeを終了",
        "settings.solanaWallet": "Solanaウォレット",
        "settings.enableSolana": "USDCウォレットを有効にする",
        "settings.solanaNetwork": "ネットワーク",
        "settings.solanaAddress": "ウォレットアドレス",
        "settings.usdcBalance": "USDC残高",
        "settings.solanaMonitoring": "入金を監視中",
        "settings.solanaStopped": "監視停止中",
        "settings.solanaHelp": "クレジットをSolana USDCに接続。10,000クレジット = $1 USDC。入出金はオンチェーンで行われます。",
        "wallet.solana.title": "Solanaウォレット",
        "wallet.solana.address": "入金アドレス",
        "wallet.solana.onChainBalance": "オンチェーンUSDC",
        "wallet.solana.depositTitle": "USDCを入金",
        "wallet.solana.depositInstructions": "上記のSolanaアドレスにUSDC (SPL) を送信してください。入金は自動検出され、10,000クレジット = $1 USDCのレートでクレジットに変換されます。",
        "wallet.solana.withdrawTitle": "USDCとして出金",
        "wallet.solana.creditsAmount": "クレジット",
        "wallet.solana.destinationAddress": "Solanaアドレス",
        "wallet.solana.withdrawButton": "出金",

        "agent.connect": "Agentを接続",
        "agent.serverRunning": "APIサーバー稼働中",
        "agent.serverStarting": "APIサーバー起動中...",
        "agent.generateKey": "APIキーを生成",
        "agent.saveKeyWarning": "このキーを保存してください——再表示されません",
        "agent.quickSetup": "クイックセットアップ",
        "agent.advanced": "詳細",
        "agent.revoked": "無効化済",
        "agent.revoke": "無効化",
        "agent.generateAnother": "別のキーを生成",
        "agent.allowNetwork": "ネットワークアクセスを許可",
        "agent.networkOn": "ネットワーク上の他のデバイスからのリクエストを受付中",
        "agent.networkOff": "このMacからのリクエストのみ受付（localhost）",
        "agent.footer": "OpenAI互換クライアントに対応——Claude Code、Cursor、Hermes、OpenClaw、Python SDKなど。",

        "cluster.title": "LANクラスタ",
        "cluster.enable": "クラスタを有効にする",
        "cluster.searchingDevices": "ネットワーク上のデバイスを検索中...",
        "cluster.connectedPeers": "接続中のピア",
        "cluster.noPeers": "ピアが見つかりません",

        "wan.title": "WAN P2Pネットワーク",
        "wan.enable": "WANを有効にする",
        "wan.connectedPeers": "接続中のピア",
        "wan.noPeers": "WANピアに未接続",

        "common.copy": "コピー",
        "common.copied": "コピー済",
        "common.phone": "電話",
        "common.email": "メール",
        "common.devices": "デバイス",
        "common.signingIn": "ログイン中...",

        "day.mon": "月",
        "day.tue": "火",
        "day.wed": "水",
        "day.thu": "木",
        "day.fri": "金",
        "day.sat": "土",
        "day.sun": "日",

        "thermal.nominal": "正常",
        "thermal.fair": "やや高",
        "thermal.serious": "高温",
        "thermal.critical": "危険",
        "power.ac": "電源",
        "power.battery": "バッテリー",
    ]

    // MARK: - Spanish

    private static let es: [String: String] = [
        "sidebar.dashboard": "Panel",
        "sidebar.chat": "Chat",
        "sidebar.models": "Modelos",
        "sidebar.network": "Red",
        "sidebar.cluster": "Clúster",
        "sidebar.wan": "WAN",
        "sidebar.wallet": "Billetera",
        "sidebar.devices": "Dispositivos",
        "sidebar.settings": "Ajustes",

        "dashboard.title": "Panel",
        "dashboard.hardware": "Hardware",
        "dashboard.engine": "Motor",
        "dashboard.noModelLoaded": "Ningún modelo cargado",
        "dashboard.browseModels": "Explorar modelos",
        "dashboard.unload": "Descargar",
        "dashboard.quickActions": "Acciones rápidas",
        "dashboard.newChat": "Nuevo chat",
        "dashboard.copyAPIURL": "Copiar URL de API",
        "dashboard.cluster": "Clúster",
        "dashboard.wan": "Red WAN",
        "dashboard.credits": "Créditos",
        "dashboard.view": "Ver",
        "dashboard.searchingPeers": "Buscando pares...",
        "dashboard.devices": "%d dispositivos",
        "dashboard.total": "%d GB total",
        "dashboard.wanPeers": "%d pares WAN",
        "dashboard.connectingWAN": "Conectando a la red WAN...",
        "dashboard.api": "API",
        "dashboard.throttle": "Límite",

        "chat.title": "Chat",
        "chat.placeholder": "Escribe un mensaje...",
        "chat.send": "Enviar",
        "chat.thinking": "Pensando...",
        "chat.noModel": "Carga un modelo para empezar a chatear",
        "chat.you": "Tú",
        "chat.assistant": "Asistente",
        "chat.newConversation": "Nueva conversación",
        "chat.noModelLoaded": "No hay modelo cargado.",
        "chat.goToModels": "Ve a **Modelos** para descargar y cargar uno.",
        "chat.startConversation": "Inicia una conversación",
        "chat.typeBelow": "Escribe un mensaje abajo para comenzar",
        "chat.noModelResponse": "No hay modelo cargado. Ve a Modelos para descargar y cargar uno.",
        "chat.message": "Mensaje...",

        "models.title": "Modelos",
        "models.search": "Buscar modelos...",
        "models.available": "%d modelos disponibles para tu hardware",
        "models.gbAvailable": "%d GB disponibles",
        "models.load": "Cargar",
        "models.unload": "Descargar",
        "models.download": "Descargar",
        "models.switchModel": "¿Cambiar modelo?",
        "models.switchConfirm": "Esto descargará el modelo actual y cargará %@.",
        "models.switchButton": "Cambiar",
        "models.cancel": "Cancelar",
        "models.downloadComplete": "Descarga completa",
        "models.readyToLoad": "%@ está listo. ¿Cargarlo ahora? Esto descargará el modelo actual.",
        "models.notNow": "Ahora no",
        "models.preparing": "Preparando…",
        "models.loaded": "CARGADO",
        "models.checking": "VERIFICANDO",
        "models.loading": "CARGANDO",
        "models.downloading": "DESC",
        "models.ready": "LISTO",

        "wallet.title": "Billetera",
        "wallet.balance": "Saldo de créditos",
        "wallet.credits": "créditos",
        "wallet.sendCredits": "Enviar créditos",
        "wallet.connectCluster": "Conéctate a un clúster para enviar créditos",
        "wallet.selectPeer": "Seleccionar par...",
        "wallet.amount": "Cantidad",
        "wallet.memo": "Nota (opcional)",
        "wallet.send": "Enviar",
        "wallet.whatCanBuy": "¿Qué puedes hacer con tus créditos?",
        "wallet.quickQuestion": "Pregunta rápida",
        "wallet.quickQuestionDetail": "Una conversación breve",
        "wallet.writeEmail": "Escribir un email o ensayo",
        "wallet.writeEmailDetail": "Varios párrafos de texto generado",
        "wallet.debugCode": "Depurar código",
        "wallet.debugCodeDetail": "Pega código, obtén explicación y corrección",
        "wallet.summarize": "Resumir un documento largo",
        "wallet.summarizeDetail": "Introduce texto extenso, obtén un resumen",
        "wallet.balancePlenty": "Tienes créditos de sobra para uso intensivo.",
        "wallet.balanceGood": "Suficiente para docenas de conversaciones.",
        "wallet.balanceOk": "Suficiente para varias conversaciones hoy.",
        "wallet.balanceLow": "Quedando poco — gana más sirviendo a otros nodos.",
        "wallet.balanceEmpty": "Sin créditos aún. Activa el clúster para empezar a ganar.",
        "wallet.pricingFooter": "Los costos varían según el tamaño del modelo — los más pequeños son baratos, los grandes dan mejores respuestas. Ganas créditos automáticamente cuando otros dispositivos usan tu Mac para inferencia.",
        "wallet.summary": "Resumen",
        "wallet.earned": "Ganado",
        "wallet.spent": "Gastado",
        "wallet.recentTransactions": "Transacciones recientes",
        "wallet.noTransactions": "Sin transacciones aún",

        "settings.title": "Ajustes",
        "settings.account": "Cuenta",
        "settings.notSignedIn": "Sin sesión",
        "settings.signInSubtitle": "Inicia sesión para sincronizar dispositivos y respaldar tu billetera",
        "settings.signIn": "Iniciar sesión",
        "settings.signOut": "Cerrar sesión",
        "settings.localMode": "Modo local",
        "settings.localModeSubtitle": "Configura Supabase para habilitar inicio de sesión y sincronización",
        "settings.general": "General",
        "settings.language": "Idioma",
        "settings.launchAtLogin": "Iniciar al encender",
        "settings.lanCluster": "Clúster LAN",
        "settings.enableLAN": "Activar descubrimiento LAN",
        "settings.clusterPasscode": "Contraseña del clúster:",
        "settings.optional": "Opcional",
        "settings.peersConnected": "%d par(es) conectado(s)",
        "settings.searchingPeers": "Buscando pares...",
        "settings.orgReservation": "Reserva de capacidad: %d%%",
        "settings.orgReservationHelp": "Los nodos con la misma contraseña forman tu organización. La capacidad reservada prioriza a los miembros.",
        "settings.wanP2P": "Red P2P WAN",
        "settings.enableWAN": "Activar WAN",
        "settings.relayServer": "Servidor relay:",
        "settings.wanPeers": "%d par(es) WAN",
        "settings.connectingRelay": "Conectando al relay...",
        "settings.natType": "Tipo de NAT",
        "settings.contributionSchedule": "Horario de contribución",
        "settings.preset": "Preajuste",
        "settings.onlyPluggedIn": "Solo conectado a corriente",
        "settings.onlyWiFi": "Solo en Wi-Fi",
        "settings.editSchedule": "Editar horario",
        "settings.hideSchedule": "Ocultar horario",
        "settings.scheduleHelp": "Controla cuándo tu máquina atiende solicitudes de red. La inferencia local siempre está disponible.",
        "settings.credits": "Créditos",
        "settings.balance": "Saldo",
        "settings.totalEarned": "Total ganado",
        "settings.totalSpent": "Total gastado",
        "settings.viewWallet": "Ver billetera",
        "settings.modelStorage": "Almacenamiento",
        "settings.maxStorage": "Almacenamiento máximo: %d GB",
        "settings.hardware": "Hardware",
        "settings.chip": "Chip",
        "settings.ram": "RAM",
        "settings.gpuCores": "Núcleos GPU",
        "settings.memBandwidth": "Ancho de banda",
        "settings.deviceTier": "Categoría",
        "settings.about": "Acerca de",
        "settings.version": "Versión",
        "settings.engine": "Motor",
        "settings.sourceCode": "Código fuente",
        "settings.keepAwake": "Mantener Mac despierto",
        "settings.keepAwakeHelp": "Evita que tu Mac entre en suspensión para que siga conectado al pool de inferencia. La pantalla aún puede apagarse.",
        "settings.quit": "Salir de Teale",
        "settings.solanaWallet": "Billetera Solana",
        "settings.enableSolana": "Activar billetera USDC",
        "settings.solanaNetwork": "Red",
        "settings.solanaAddress": "Dirección de billetera",
        "settings.usdcBalance": "Saldo USDC",
        "settings.solanaMonitoring": "Monitoreando depósitos",
        "settings.solanaStopped": "Monitoreo detenido",
        "settings.solanaHelp": "Conecta tus créditos a Solana USDC. 10,000 créditos = $1 USDC. Depósitos y retiros son en cadena.",
        "wallet.solana.title": "Billetera Solana",
        "wallet.solana.address": "Tu dirección de depósito",
        "wallet.solana.onChainBalance": "USDC en cadena",
        "wallet.solana.depositTitle": "Depositar USDC",
        "wallet.solana.depositInstructions": "Envía USDC (SPL) en Solana a la dirección de arriba. Los depósitos se detectan automáticamente y se convierten a créditos a 10,000 créditos por $1 USDC.",
        "wallet.solana.withdrawTitle": "Retirar como USDC",
        "wallet.solana.creditsAmount": "Créditos",
        "wallet.solana.destinationAddress": "Dirección Solana",
        "wallet.solana.withdrawButton": "Retirar",

        "agent.connect": "Conecta tu agente",
        "agent.serverRunning": "Servidor API activo",
        "agent.serverStarting": "Servidor API iniciando...",
        "agent.generateKey": "Generar clave API",
        "agent.saveKeyWarning": "Guarda esta clave — no se mostrará de nuevo",
        "agent.quickSetup": "Configuración rápida",
        "agent.advanced": "Avanzado",
        "agent.revoked": "Revocada",
        "agent.revoke": "Revocar",
        "agent.generateAnother": "Generar otra clave",
        "agent.allowNetwork": "Permitir acceso de red",
        "agent.networkOn": "Aceptando solicitudes de otros dispositivos en la red",
        "agent.networkOff": "Solo aceptando solicitudes locales (localhost)",
        "agent.footer": "Compatible con cualquier cliente OpenAI — Claude Code, Cursor, Hermes, OpenClaw, Python SDK y más.",

        "cluster.title": "Clúster LAN",
        "cluster.enable": "Activar clúster",
        "cluster.searchingDevices": "Buscando dispositivos en tu red...",
        "cluster.connectedPeers": "Pares conectados",
        "cluster.noPeers": "No se encontraron pares",

        "wan.title": "Red P2P WAN",
        "wan.enable": "Activar WAN",
        "wan.connectedPeers": "Pares conectados",
        "wan.noPeers": "Sin pares WAN conectados",

        "common.copy": "Copiar",
        "common.copied": "Copiado",
        "common.phone": "Teléfono",
        "common.email": "Email",
        "common.devices": "Dispositivos",
        "common.signingIn": "Iniciando sesión...",

        "day.mon": "Lun",
        "day.tue": "Mar",
        "day.wed": "Mié",
        "day.thu": "Jue",
        "day.fri": "Vie",
        "day.sat": "Sáb",
        "day.sun": "Dom",

        "thermal.nominal": "Normal",
        "thermal.fair": "Aceptable",
        "thermal.serious": "Elevada",
        "thermal.critical": "Crítica",
        "power.ac": "Corriente",
        "power.battery": "Batería",
    ]

    // MARK: - French

    private static let fr: [String: String] = [
        "sidebar.dashboard": "Tableau de bord",
        "sidebar.chat": "Chat",
        "sidebar.models": "Modèles",
        "sidebar.network": "Réseau",
        "sidebar.cluster": "Cluster",
        "sidebar.wan": "WAN",
        "sidebar.wallet": "Portefeuille",
        "sidebar.devices": "Appareils",
        "sidebar.settings": "Réglages",

        "dashboard.title": "Tableau de bord",
        "dashboard.hardware": "Matériel",
        "dashboard.engine": "Moteur",
        "dashboard.noModelLoaded": "Aucun modèle chargé",
        "dashboard.browseModels": "Parcourir les modèles",
        "dashboard.unload": "Décharger",
        "dashboard.quickActions": "Actions rapides",
        "dashboard.newChat": "Nouveau chat",
        "dashboard.copyAPIURL": "Copier l'URL API",
        "dashboard.cluster": "Cluster",
        "dashboard.wan": "Réseau WAN",
        "dashboard.credits": "Crédits",
        "dashboard.view": "Voir",
        "dashboard.searchingPeers": "Recherche de pairs...",
        "dashboard.devices": "%d appareils",
        "dashboard.total": "%d Go au total",
        "dashboard.wanPeers": "%d pairs WAN",
        "dashboard.connectingWAN": "Connexion au réseau WAN...",
        "dashboard.api": "API",
        "dashboard.throttle": "Régulation",

        "chat.title": "Chat",
        "chat.placeholder": "Tapez un message...",
        "chat.send": "Envoyer",
        "chat.thinking": "Réflexion...",
        "chat.noModel": "Chargez un modèle pour commencer à discuter",
        "chat.you": "Vous",
        "chat.assistant": "Assistant",
        "chat.newConversation": "Nouvelle conversation",
        "chat.noModelLoaded": "Aucun modèle chargé.",
        "chat.goToModels": "Allez dans **Modèles** pour en télécharger et charger un.",
        "chat.startConversation": "Démarrer une conversation",
        "chat.typeBelow": "Tapez un message ci-dessous pour commencer",
        "chat.noModelResponse": "Aucun modèle chargé. Allez dans Modèles pour en télécharger et charger un.",
        "chat.message": "Message...",

        "models.title": "Modèles",
        "models.search": "Rechercher des modèles...",
        "models.available": "%d modèles disponibles pour votre matériel",
        "models.gbAvailable": "%d Go disponibles",
        "models.load": "Charger",
        "models.unload": "Décharger",
        "models.download": "Télécharger",
        "models.switchModel": "Changer de modèle ?",
        "models.switchConfirm": "Ceci déchargera le modèle actuel et chargera %@.",
        "models.switchButton": "Changer",
        "models.cancel": "Annuler",
        "models.downloadComplete": "Téléchargement terminé",
        "models.readyToLoad": "%@ est prêt. Le charger maintenant ? Le modèle actuel sera déchargé.",
        "models.notNow": "Pas maintenant",
        "models.preparing": "Préparation…",
        "models.loaded": "CHARGÉ",
        "models.checking": "VÉRIF.",
        "models.loading": "CHARGMT",
        "models.downloading": "TÉLÉCH",
        "models.ready": "PRÊT",

        "wallet.title": "Portefeuille",
        "wallet.balance": "Solde de crédits",
        "wallet.credits": "crédits",
        "wallet.sendCredits": "Envoyer des crédits",
        "wallet.connectCluster": "Connectez-vous à un cluster pour envoyer des crédits",
        "wallet.selectPeer": "Sélectionner un pair...",
        "wallet.amount": "Montant",
        "wallet.memo": "Note (facultatif)",
        "wallet.send": "Envoyer",
        "wallet.whatCanBuy": "Que pouvez-vous faire avec vos crédits ?",
        "wallet.quickQuestion": "Question rapide",
        "wallet.quickQuestionDetail": "Une courte conversation",
        "wallet.writeEmail": "Rédiger un email ou un texte",
        "wallet.writeEmailDetail": "Quelques paragraphes de texte généré",
        "wallet.debugCode": "Déboguer du code",
        "wallet.debugCodeDetail": "Collez du code, obtenez une explication et un correctif",
        "wallet.summarize": "Résumer un long document",
        "wallet.summarizeDetail": "Fournissez un texte long, obtenez un résumé",
        "wallet.balancePlenty": "Vous avez largement assez de crédits pour un usage intensif.",
        "wallet.balanceGood": "Assez pour des dizaines de conversations.",
        "wallet.balanceOk": "Suffisant pour plusieurs conversations aujourd'hui.",
        "wallet.balanceLow": "Bientôt épuisé — gagnez plus en servant d'autres nœuds.",
        "wallet.balanceEmpty": "Pas encore de crédits. Activez le cluster pour commencer à en gagner.",
        "wallet.pricingFooter": "Les coûts varient selon la taille du modèle — les petits sont moins chers, les grands donnent de meilleures réponses. Vous gagnez des crédits automatiquement quand d'autres appareils utilisent votre Mac pour l'inférence.",
        "wallet.summary": "Résumé",
        "wallet.earned": "Gagné",
        "wallet.spent": "Dépensé",
        "wallet.recentTransactions": "Transactions récentes",
        "wallet.noTransactions": "Aucune transaction",

        "settings.title": "Réglages",
        "settings.account": "Compte",
        "settings.notSignedIn": "Non connecté",
        "settings.signInSubtitle": "Connectez-vous pour synchroniser vos appareils et sauvegarder votre portefeuille",
        "settings.signIn": "Se connecter",
        "settings.signOut": "Se déconnecter",
        "settings.localMode": "Mode local",
        "settings.localModeSubtitle": "Configurez Supabase pour activer la connexion et la synchronisation",
        "settings.general": "Général",
        "settings.language": "Langue",
        "settings.launchAtLogin": "Lancer au démarrage",
        "settings.lanCluster": "Cluster LAN",
        "settings.enableLAN": "Activer la découverte LAN",
        "settings.clusterPasscode": "Code du cluster :",
        "settings.optional": "Facultatif",
        "settings.peersConnected": "%d pair(s) connecté(s)",
        "settings.searchingPeers": "Recherche de pairs...",
        "settings.orgReservation": "Réservation de capacité : %d%%",
        "settings.orgReservationHelp": "Les nœuds avec le même code forment votre organisation. La capacité réservée sert les membres en priorité.",
        "settings.wanP2P": "Réseau P2P WAN",
        "settings.enableWAN": "Activer le WAN",
        "settings.relayServer": "Serveur relais :",
        "settings.wanPeers": "%d pair(s) WAN",
        "settings.connectingRelay": "Connexion au relais...",
        "settings.natType": "Type de NAT",
        "settings.contributionSchedule": "Planning de contribution",
        "settings.preset": "Préréglage",
        "settings.onlyPluggedIn": "Uniquement branché",
        "settings.onlyWiFi": "Uniquement en Wi-Fi",
        "settings.editSchedule": "Modifier le planning",
        "settings.hideSchedule": "Masquer le planning",
        "settings.scheduleHelp": "Contrôle quand votre machine traite les requêtes réseau. L'inférence locale est toujours disponible.",
        "settings.credits": "Crédits",
        "settings.balance": "Solde",
        "settings.totalEarned": "Total gagné",
        "settings.totalSpent": "Total dépensé",
        "settings.viewWallet": "Voir le portefeuille",
        "settings.modelStorage": "Stockage des modèles",
        "settings.maxStorage": "Stockage maximum : %d Go",
        "settings.hardware": "Matériel",
        "settings.chip": "Puce",
        "settings.ram": "RAM",
        "settings.gpuCores": "Cœurs GPU",
        "settings.memBandwidth": "Bande passante",
        "settings.deviceTier": "Catégorie",
        "settings.about": "À propos",
        "settings.version": "Version",
        "settings.engine": "Moteur",
        "settings.sourceCode": "Code source",
        "settings.keepAwake": "Garder le Mac éveillé",
        "settings.keepAwakeHelp": "Empêche votre Mac de se mettre en veille pour qu'il reste en ligne dans le pool d'inférence. L'écran peut toujours s'éteindre.",
        "settings.quit": "Quitter Teale",
        "settings.solanaWallet": "Portefeuille Solana",
        "settings.enableSolana": "Activer le portefeuille USDC",
        "settings.solanaNetwork": "Réseau",
        "settings.solanaAddress": "Adresse du portefeuille",
        "settings.usdcBalance": "Solde USDC",
        "settings.solanaMonitoring": "Surveillance des dépôts",
        "settings.solanaStopped": "Surveillance arrêtée",
        "settings.solanaHelp": "Connectez vos crédits à Solana USDC. 10 000 crédits = 1 $ USDC. Les dépôts et retraits sont on-chain.",
        "wallet.solana.title": "Portefeuille Solana",
        "wallet.solana.address": "Votre adresse de dépôt",
        "wallet.solana.onChainBalance": "USDC on-chain",
        "wallet.solana.depositTitle": "Déposer des USDC",
        "wallet.solana.depositInstructions": "Envoyez des USDC (SPL) sur Solana à l'adresse ci-dessus. Les dépôts sont détectés automatiquement et convertis en crédits à 10 000 crédits pour 1 $ USDC.",
        "wallet.solana.withdrawTitle": "Retirer en USDC",
        "wallet.solana.creditsAmount": "Crédits",
        "wallet.solana.destinationAddress": "Adresse Solana",
        "wallet.solana.withdrawButton": "Retirer",

        "agent.connect": "Connectez votre agent",
        "agent.serverRunning": "Serveur API actif",
        "agent.serverStarting": "Serveur API en démarrage...",
        "agent.generateKey": "Générer une clé API",
        "agent.saveKeyWarning": "Sauvegardez cette clé — elle ne sera plus affichée",
        "agent.quickSetup": "Configuration rapide",
        "agent.advanced": "Avancé",
        "agent.revoked": "Révoquée",
        "agent.revoke": "Révoquer",
        "agent.generateAnother": "Générer une autre clé",
        "agent.allowNetwork": "Autoriser l'accès réseau",
        "agent.networkOn": "Accepte les requêtes des autres appareils du réseau",
        "agent.networkOff": "Accepte uniquement les requêtes locales (localhost)",
        "agent.footer": "Compatible avec tout client OpenAI — Claude Code, Cursor, Hermes, OpenClaw, SDK Python et plus.",

        "cluster.title": "Cluster LAN",
        "cluster.enable": "Activer le cluster",
        "cluster.searchingDevices": "Recherche d'appareils sur votre réseau...",
        "cluster.connectedPeers": "Pairs connectés",
        "cluster.noPeers": "Aucun pair trouvé",

        "wan.title": "Réseau P2P WAN",
        "wan.enable": "Activer le WAN",
        "wan.connectedPeers": "Pairs connectés",
        "wan.noPeers": "Aucun pair WAN connecté",

        "common.copy": "Copier",
        "common.copied": "Copié",
        "common.phone": "Téléphone",
        "common.email": "Email",
        "common.devices": "Appareils",
        "common.signingIn": "Connexion...",

        "day.mon": "Lun",
        "day.tue": "Mar",
        "day.wed": "Mer",
        "day.thu": "Jeu",
        "day.fri": "Ven",
        "day.sat": "Sam",
        "day.sun": "Dim",

        "thermal.nominal": "Normal",
        "thermal.fair": "Correct",
        "thermal.serious": "Élevée",
        "thermal.critical": "Critique",
        "power.ac": "Secteur",
        "power.battery": "Batterie",
    ]
}
