import Foundation
import SharedTypes

// MARK: - Response Synthesizer

/// Combines sub-task results into a coherent final response.
/// Two strategies: ordered concatenation (fast) or LLM synthesis (coherent).
public actor ResponseSynthesizer {

    private let synthesisProvider: (any InferenceProvider)?

    /// Create a synthesizer.
    /// - Parameter synthesisProvider: Optional LLM provider for blending responses.
    ///   If nil, uses ordered concatenation only.
    public init(synthesisProvider: (any InferenceProvider)? = nil) {
        self.synthesisProvider = synthesisProvider
    }

    /// Synthesize sub-task results into a final response.
    public func synthesize(
        results: [SubTaskResult],
        originalRequest: ChatCompletionRequest,
        synthesisPrompt: String
    ) async throws -> String {
        guard !results.isEmpty else { return "" }

        // Single result — no synthesis needed
        if results.count == 1 {
            return results[0].content
        }

        // If we have a synthesis provider and a non-trivial synthesis prompt, use LLM blending
        if let provider = synthesisProvider, !synthesisPrompt.isEmpty {
            return try await llmSynthesis(
                results: results,
                originalRequest: originalRequest,
                synthesisPrompt: synthesisPrompt,
                provider: provider
            )
        }

        // Default: ordered concatenation with section breaks
        return concatenate(results: results)
    }

    // MARK: - Strategies

    /// Simple ordered concatenation with separator.
    private func concatenate(results: [SubTaskResult]) -> String {
        results
            .map(\.content)
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
            .joined(separator: "\n\n")
    }

    /// LLM-based synthesis: feeds all sub-task outputs to a model with instructions to blend.
    private func llmSynthesis(
        results: [SubTaskResult],
        originalRequest: ChatCompletionRequest,
        synthesisPrompt: String,
        provider: any InferenceProvider
    ) async throws -> String {
        let originalMessage = originalRequest.messages.last(where: { $0.role == "user" })?.content ?? ""

        // Build the synthesis input
        var parts: [String] = []
        for (i, result) in results.enumerated() {
            parts.append("--- Part \(i + 1) (from \(result.model)) ---\n\(result.content)")
        }
        let partsText = parts.joined(separator: "\n\n")

        let prompt = """
        Original request: \(originalMessage)

        The following parts were generated by different specialized models. \
        \(synthesisPrompt)

        \(partsText)
        """

        let request = ChatCompletionRequest(
            messages: [
                APIMessage(role: "system", content: "You are a synthesis assistant. Combine the provided parts into a single coherent response. Maintain the voice and quality of each part while ensuring smooth transitions. Do not add new information — only blend what is given."),
                APIMessage(role: "user", content: prompt),
            ],
            maxTokens: originalRequest.maxTokens
        )

        let response = try await provider.generateFull(request: request)
        return response.choices.first?.message.content ?? concatenate(results: results)
    }
}
