import XCTest
@testable import PINKit

/// Cross-language contract tests: the fixture is generated by the Rust
/// suite (protocol/tests/fixtures/signed_netmap.json, regenerate with
/// `cargo run -p teale-protocol --example gen_pin_fixture`). If these fail
/// after a fixture change, canonicalization drifted between platforms.
final class PINNetmapTests: XCTestCase {

    private func fixtureData() throws -> Data {
        // Tests run from the package root's parent; resolve relative to this
        // source file so the path survives both Xcode and swift test.
        let here = URL(fileURLWithPath: #filePath)
        let repoRoot = here
            .deletingLastPathComponent()  // PINKitTests
            .deletingLastPathComponent()  // Tests
            .deletingLastPathComponent()  // mac-app
            .deletingLastPathComponent()  // repo root
        let fixture = repoRoot.appendingPathComponent("protocol/tests/fixtures/signed_netmap.json")
        return try Data(contentsOf: fixture)
    }

    func testFixtureParsesAndVerifies() throws {
        let signed = try PINNetmap.parse(try fixtureData())
        XCTAssertEqual(signed.netmap.generation, 7)
        XCTAssertEqual(signed.netmap.members.count, 2)
        XCTAssertEqual(signed.netmap.members[0].deviceId, "dev-windows-01")
        XCTAssertTrue(
            PINNetmap.verify(signed, pinnedGatewayKey: signed.gatewayPubkey),
            "Rust-signed fixture must verify — canonical JSON drift if this fails"
        )
    }

    func testTamperedNetmapFailsVerification() throws {
        let signed = try PINNetmap.parse(try fixtureData())
        var raw = signed.rawNetmapObject as [String: Any]
        var members = raw["members"] as! [[String: Any]]
        members[1]["disabled"] = false
        raw["members"] = members
        let tampered = SignedPinNetmap(
            netmap: signed.netmap,
            gatewayPubkey: signed.gatewayPubkey,
            signature: signed.signature,
            rawNetmapObject: raw as! [String: Any & Sendable]
        )
        XCTAssertFalse(PINNetmap.verify(tampered, pinnedGatewayKey: signed.gatewayPubkey))
    }

    func testWrongPinnedKeyFailsVerification() throws {
        let signed = try PINNetmap.parse(try fixtureData())
        XCTAssertFalse(PINNetmap.verify(signed, pinnedGatewayKey: String(repeating: "00", count: 32)))
    }

    func testStaleness() throws {
        let signed = try PINNetmap.parse(try fixtureData())
        XCTAssertFalse(PINNetmap.isStale(signed, now: signed.netmap.issuedAt + PINNetmap.maxAgeSeconds))
        XCTAssertTrue(PINNetmap.isStale(signed, now: signed.netmap.issuedAt + PINNetmap.maxAgeSeconds + 1))
    }

    func testCanonicalJSONMatchesRustShape() throws {
        let scrambled: [String: Any] = [
            "zeta": 1,
            "alpha": ["nested_z": 1, "nested_a": [["b": 2, "a": 1]]],
        ]
        let bytes = try PINNetmap.canonicalJSON(scrambled)
        XCTAssertEqual(
            String(data: bytes, encoding: .utf8),
            #"{"alpha":{"nested_a":[{"a":1,"b":2}],"nested_z":1},"zeta":1}"#
        )
    }

    func testLocalSettingsDefaults() throws {
        let decoded = try JSONDecoder().decode(LocalPinSettings.self, from: Data("{}".utf8))
        XCTAssertTrue(decoded.allowRemoteModels)
        XCTAssertFalse(decoded.dinPriorityEqual)
        XCTAssertTrue(decoded.dinContribute)
    }
}
