#!/bin/sh
# Generate BuildVersion.swift with git commit hash and build date.
# Called before swift build or xcodebuild.

set -e

OUTFILE="Sources/SharedTypes/BuildVersion.swift"
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
DATE=$(date -u '+%Y-%m-%d %H:%M UTC')
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

cat > "$OUTFILE" << EOF
// Auto-generated by scripts/generate-version.sh — do not edit manually.
public enum BuildVersion {
    public static let commit = "$COMMIT"
    public static let date = "$DATE"
    public static let branch = "$BRANCH"
    public static let display = "$COMMIT ($DATE)"
}
EOF
